#!/usr/bin/env python3
"""STAC for the FTW Sentinel-2 planting/harvest composites ("features").

Two collections, one per year (`s2-planting-harvest-composites-2024` / `-2025`).
Each collection (committed to the repo) carries the global Zarr mosaic as a
collection asset and a **STAC-GeoParquet** asset (the item index). The per-tile
items (harvest + planting COG assets) and the items.parquet are **S3-only** —
generated by this script, written under `features/<year>/…` on S3, and NEVER
committed (they're .gitignore'd). At ~22.7k tiles/year that's the scalable
pattern; the collection points at the stac-geoparquet rather than enumerating
tens of thousands of item links.

Subcommands:
    build_features_items.py collections                 # write the 2 collection.json + README + llms (repo)
    build_features_items.py items 2024 [--limit N]      # generate per-tile items + items.parquet (S3); run on rails
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

PUB = "https://data.source.coop/ftw/global-data"
S3_BUCKET = "us-west-2.opendata.source.coop"
S3_PREFIX = "tge-labs/ftw-global-data"
COG_BASE = f"{PUB}/features/cogs/alpha"
ZARR_HREF = f"{PUB}/features/zarr/alpha/global.zarr"
# Read the COG index over public HTTPS (duckdb s3:// hits an SSL/virtual-host issue
# with the dotted Source Coop bucket name).
INDEX_PARQUET = f"{PUB}/features/cogs/alpha/index.parquet"
FTW_URL = "https://fieldsofthe.world"
FTW_BENCHMARK_DATA = "https://source.coop/kerner-lab/fields-of-the-world"

PROJ_EXT = "https://stac-extensions.github.io/projection/v2.0.0/schema.json"
EO_EXT = "https://stac-extensions.github.io/eo/v2.0.0/schema.json"
GRID_EXT = "https://stac-extensions.github.io/grid/v1.1.0/schema.json"
ITEM_ASSETS_EXT = "https://stac-extensions.github.io/item-assets/v1.0.0/schema.json"
SCI_EXT = "https://stac-extensions.github.io/scientific/v1.0.0/schema.json"

# Source Sentinel-2 imagery. derived_from -> the official ESA Copernicus Data Space
# Ecosystem STAC (Sentinel-2 L2A); via -> the AWS Open Data / Earth Search L2A COG
# catalog that indexes the `sentinel-cogs` bucket these composites were physically built from.
S2_MISSION = "https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-2"
S2_L2A_OFFICIAL = "https://stac.dataspace.copernicus.eu/v1/collections/sentinel-2-l2a"
S2_L2A_COGS = "https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a"

# The two per-year collections live under one STAC sub-catalog, so the root shows a
# single "composites" entry that expands into 2024/2025.
FEAT_CATALOG_ID = "s2-planting-harvest-composites"
FEAT_CATALOG_TITLE = "FTW Global — Sentinel-2 Planting & Harvest Composites"
THUMB_HREF = f"{PUB}/features/thumbnail.png"

SPECTRAL_BANDS = [
    {"name": "B02", "eo:common_name": "blue", "eo:center_wavelength": 0.49},
    {"name": "B03", "eo:common_name": "green", "eo:center_wavelength": 0.56},
    {"name": "B04", "eo:common_name": "red", "eo:center_wavelength": 0.665},
    {"name": "B08", "eo:common_name": "nir", "eo:center_wavelength": 0.842},
    {"name": "N_VALID_PIXELS",
     "description": "Count of valid Sentinel-2 scenes after quality-flag masking (not a reflectance band)."},
]
SCI_PUBLICATIONS = [
    {"doi": "10.48550/arXiv.2409.16252",
     "citation": "Kerner, H. et al. (2025). Fields of the World: A Machine Learning Benchmark "
                 "Dataset for Global Agricultural Field Boundary Segmentation. AAAI-2025. arXiv:2409.16252."},
    {"doi": "10.48550/arXiv.2603.27101",
     "citation": "Muhawenayo, G. et al. (2026). PRUE: A Practical Recipe for Field Boundary "
                 "Segmentation at Scale. arXiv:2603.27101."},
    {"doi": "10.48550/arXiv.2602.08131",
     "citation": "Corley, I. et al. (2026). Fields of The World: A Field Guide for Extracting "
                 "Agricultural Field Boundaries. arXiv:2602.08131."},
]
_DESC = (
    "Sentinel-2 **planting- and harvest-season median composites** at 10 m — the model-input "
    "features for the FTW Global field-boundary predictions. For each grid tile and season, "
    "~5–10 quality-masked Sentinel-2 scenes (selected by latitude-based day-of-year heuristics) "
    "are reduced to a per-pixel median; bands are B02/B03/B04/B08 plus N_VALID_PIXELS, in the "
    "tile's native UTM zone. Part of [Fields of the World]({ftw}). These composites feed the "
    "**PRUE** U-Net model ([Muhawenayo et al. 2026](https://arxiv.org/abs/2603.27101); 76% IoU / "
    "47% object-F1 on the [Fields of the World benchmark]({bench}) of 70,462 Sentinel-2 samples "
    "across 24 countries, [Kerner et al. 2025](https://arxiv.org/abs/2409.16252)), whose outputs "
    "are the `predictions` collections. Also available as a single global EPSG:4326 Zarr mosaic "
    "(collection `data` asset), stackable with the prediction Zarr.\n\n"
    "**Items & index:** ~22.7k per-tile items (each with a `planting` and `harvest` COG asset) "
    "are indexed by the collection's STAC-GeoParquet asset (`items.parquet`); query that rather "
    "than enumerating item links."
).format(ftw=FTW_URL, bench=FTW_BENCHMARK_DATA)


def collection_id(year):
    return f"s2-planting-harvest-composites-{year}"


def build_collection(year):
    base = f"{PUB}/features/{year}"
    asset_band_common = {"gsd": 10, "data_type": "float32", "bands": SPECTRAL_BANDS}
    return {
        "type": "Collection",
        "stac_version": "1.1.0",
        "stac_extensions": [PROJ_EXT, EO_EXT, ITEM_ASSETS_EXT, SCI_EXT],
        "id": collection_id(year),
        "title": f"FTW Global — Sentinel-2 Planting & Harvest Composites ({year})",
        "description": _DESC,
        "license": "CC-BY-4.0",
        "keywords": ["Sentinel-2", "median composite", "agriculture", "field boundaries",
                     "Fields of the World", "FTW", "model input", "features", "10m", str(year)],
        "providers": [
            {"name": "Taylor Geospatial Institute", "roles": ["producer", "licensor"],
             "url": "https://taylorgeospatial.org/"},
            {"name": "Microsoft AI for Good Research Lab", "roles": ["producer", "processor"],
             "url": "https://www.microsoft.com/en-us/research/group/ai-for-good-research-lab/"},
            {"name": "European Space Agency / Copernicus", "roles": ["producer"],
             "url": "https://sentinels.copernicus.eu/", "description": "Sentinel-2 source imagery"},
        ],
        "extent": {
            "spatial": {"bbox": [[-180.0, -57.830146, 180.0, 83.748345]]},
            "temporal": {"interval": [[f"{year}-01-01T00:00:00Z", f"{year}-12-31T23:59:59Z"]]},
        },
        "summaries": {"gsd": [10], "eo:bands": SPECTRAL_BANDS},
        "item_assets": {
            "planting": {"type": "image/tiff; application=geotiff; profile=cloud-optimized",
                         "title": "Planting-season Sentinel-2 median composite",
                         "roles": ["data"], **asset_band_common},
            "harvest": {"type": "image/tiff; application=geotiff; profile=cloud-optimized",
                        "title": "Harvest-season Sentinel-2 median composite",
                        "roles": ["data"], **asset_band_common},
        },
        "sci:publications": SCI_PUBLICATIONS,
        "assets": {
            "thumbnail": {"href": THUMB_HREF, "type": "image/png",
                          "title": "Sentinel-2 composite preview",
                          "roles": ["thumbnail", "overview"]},
            "zarr": {"href": ZARR_HREF, "type": "application/vnd+zarr",
                     "title": "Global Sentinel-2 composite mosaic (Zarr V3, EPSG:4326, ~10 m)",
                     "description": "All tiles reprojected/resampled to EPSG:4326; dims (time, band, y, x). "
                                    "Open with xarray: xr.open_zarr(href).pipe(rasterix.assign_index).",
                     "roles": ["data", "cloud-optimized"]},
            "geoparquet-items": {"href": f"{base}/items.parquet",
                                 "type": "application/vnd.apache.parquet",
                                 "title": "STAC-GeoParquet item index (per-tile items)",
                                 "description": "STAC-GeoParquet listing all per-tile items for this "
                                                "year; the scalable item index in lieu of item links.",
                                 "roles": ["metadata"]},
            "documentation": {"href": "./llms.txt", "type": "text/markdown",
                              "title": "Agent/LLM usage guide", "roles": ["documentation"]},
            "README": {"href": "./README.md", "type": "text/markdown",
                       "title": "Human-readable README", "roles": ["metadata"]},
        },
        "links": [
            {"rel": "root", "href": "../../catalog.json", "type": "application/json",
             "title": "Fields of the World — Global"},
            {"rel": "parent", "href": "../catalog.json", "type": "application/json",
             "title": FEAT_CATALOG_TITLE},
            {"rel": "self", "href": f"{base}/collection.json", "type": "application/json",
             "title": f"FTW Global — Sentinel-2 Planting & Harvest Composites ({year})"},
            {"rel": "license", "href": "https://creativecommons.org/licenses/by/4.0/",
             "type": "text/html", "title": "CC-BY-4.0"},
            {"rel": "cite-as", "href": "https://aka.ms/ftw-global-paper", "title": "FTW Global paper"},
            {"rel": "via", "href": FTW_BENCHMARK_DATA, "type": "text/html",
             "title": "Fields of the World benchmark (training data) on Source Cooperative"},
            {"rel": "derived_from", "href": S2_L2A_OFFICIAL, "type": "application/json",
             "title": "Sentinel-2 L2A — Copernicus Data Space Ecosystem (ESA, official)"},
            {"rel": "via", "href": S2_L2A_COGS, "type": "application/json",
             "title": "Sentinel-2 L2A COGs (AWS Open Data / Earth Search — source scenes used)"},
            {"rel": "related", "href": f"{PUB}/predictions/zarr/collection.json",
             "type": "application/json", "title": "Prediction probabilities (Zarr) made from these features"},
            {"rel": "llms", "href": "./llms.txt", "type": "text/markdown",
             "title": "Agent/LLM usage guide"},
        ],
    }


def build_features_catalog():
    """A STAC Catalog grouping the per-year composite collections, so the root shows
    one 'composites' entry that expands into 2024 / 2025."""
    return {
        "type": "Catalog",
        "stac_version": "1.1.0",
        "id": FEAT_CATALOG_ID,
        "title": FEAT_CATALOG_TITLE,
        "description": (
            "Sentinel-2 planting- and harvest-season median composites (10 m) — the model-"
            "input features for the FTW Global field-boundary predictions — organized by "
            "prediction year. See each year's collection for the COGs, the global Zarr mosaic, "
            "and the STAC-GeoParquet item index."),
        "links": [
            {"rel": "root", "href": "../catalog.json", "type": "application/json",
             "title": "Fields of the World — Global"},
            {"rel": "parent", "href": "../catalog.json", "type": "application/json",
             "title": "Fields of the World — Global"},
            {"rel": "self", "href": f"{PUB}/features/catalog.json", "type": "application/json",
             "title": FEAT_CATALOG_TITLE},
            {"rel": "child", "href": "./2024/collection.json", "type": "application/json",
             "title": f"{FEAT_CATALOG_TITLE} (2024)"},
            {"rel": "child", "href": "./2025/collection.json", "type": "application/json",
             "title": f"{FEAT_CATALOG_TITLE} (2025)"},
        ],
    }


def build_item(tile_id, year, geometry, bbox, proj_code, proj_shape, proj_transform):
    iid = f"{tile_id.lower()}_{year}"
    def asset(ds, season):
        return {
            "href": f"{COG_BASE}/{ds}/{tile_id}/{year}0101.tif",
            "type": "image/tiff; application=geotiff; profile=cloud-optimized",
            "title": f"{season}-season Sentinel-2 median composite",
            "description": (f"Per-pixel median of ~5–10 quality-masked Sentinel-2 scenes over the "
                            f"{season.lower()} day-of-year window; 10 m, bands B02/B03/B04/B08 + N_VALID_PIXELS."),
            "roles": ["data"], "gsd": 10, "data_type": "float32", "bands": SPECTRAL_BANDS,
        }
    return {
        "type": "Feature", "stac_version": "1.1.0",
        "stac_extensions": [PROJ_EXT, EO_EXT, GRID_EXT],
        "id": iid, "geometry": geometry, "bbox": bbox,
        "properties": {
            "title": f"Sentinel-2 planting & harvest composites — tile {tile_id} ({year})",
            "description": (
                f"[Sentinel-2]({S2_MISSION}) planting- and harvest-season **median composites** for "
                f"MGRS tile `{tile_id}`, {year}, at 10 m — the model-input *features* for the "
                f"[Fields of the World]({FTW_URL}) global field-boundary predictions. Each composite is "
                "the per-pixel median of ~5–10 quality-masked (SCL cloud/shadow) Sentinel-2 L2A scenes "
                "selected by planting/harvest day-of-year heuristics; bands B02/B03/B04/B08 + "
                f"N_VALID_PIXELS, in the tile's native UTM zone. Derived from "
                f"[Sentinel-2 L2A]({S2_L2A_OFFICIAL}) (ESA / Copernicus). These features feed the "
                f"[PRUE](https://arxiv.org/abs/2603.27101) model whose outputs are the FTW "
                f"[predictions]({PUB}/predictions/vectors/collection.json)."),
            "datetime": f"{year}-07-01T00:00:00Z",
            "start_datetime": f"{year}-01-01T00:00:00Z",
            "end_datetime": f"{year}-12-31T23:59:59Z",
            "gsd": 10, "grid:code": f"MGRS-{tile_id}",
            "proj:code": proj_code, "proj:shape": proj_shape, "proj:transform": proj_transform,
        },
        "collection": collection_id(year),
        "assets": {"planting": asset("s2med_planting", "Planting"),
                   "harvest": asset("s2med_harvest", "Harvest")},
        "links": [
            {"rel": "root", "href": f"{PUB}/catalog.json", "type": "application/json",
             "title": "Fields of the World — Global"},
            {"rel": "collection", "href": f"{PUB}/features/{year}/collection.json",
             "type": "application/json",
             "title": f"FTW Global — Sentinel-2 Planting & Harvest Composites ({year})"},
            {"rel": "parent", "href": f"{PUB}/features/{year}/collection.json",
             "type": "application/json",
             "title": f"FTW Global — Sentinel-2 Planting & Harvest Composites ({year})"},
            {"rel": "self", "href": f"{PUB}/features/{year}/items/{iid}.json",
             "type": "application/geo+json"},
            {"rel": "derived_from", "href": S2_L2A_OFFICIAL, "type": "application/json",
             "title": "Sentinel-2 L2A — Copernicus Data Space Ecosystem (ESA, official)"},
            {"rel": "via", "href": S2_L2A_COGS, "type": "application/json",
             "title": "Sentinel-2 L2A COGs (AWS Open Data / Earth Search — source scenes used)"},
        ],
    }


def _readme(year):
    return (f"# FTW Global — Sentinel-2 Planting & Harvest Composites ({year})\n\n"
            + _DESC.replace("\\n", "\n") + "\n\n"
            "## Access\n\n"
            "```python\nimport xarray as xr, rasterix\n"
            f"ds = xr.open_zarr(\"{ZARR_HREF}\").pipe(rasterix.assign_index)  # global mosaic\n"
            "```\n\n"
            "Per-tile COGs are indexed by the STAC-GeoParquet item index "
            f"(`{PUB}/features/{year}/items.parquet`); each item has a `planting` and a `harvest` "
            "5-band COG (B02/B03/B04/B08/N_VALID_PIXELS) in its native UTM zone.\n\n"
            "## License\n\nCC-BY-4.0. Sentinel-2 imagery © Copernicus/ESA; composites by the "
            "Taylor Geospatial Institute and Microsoft AI for Good Research Lab.\n")


def _llms(year):
    return (f"# FTW Global — Sentinel-2 Planting & Harvest Composites ({year})\n\n"
            "Sentinel-2 planting/harvest median composites (10 m) — the model-input features for the "
            "FTW field-boundary predictions. Part of Fields of the World.\n\n"
            f"- Global Zarr mosaic: {ZARR_HREF} (xr.open_zarr; EPSG:4326, dims time,band,y,x)\n"
            f"- Per-tile COG items indexed by STAC-GeoParquet: {PUB}/features/{year}/items.parquet\n"
            "- Each tile item: `planting` + `harvest` COGs, bands B02/B03/B04/B08 + N_VALID_PIXELS, "
            "native UTM, 10 m.\n"
            "- Composites feed the PRUE U-Net model (arXiv:2603.27101) trained on the FTW benchmark "
            f"(data: {FTW_BENCHMARK_DATA}; arXiv:2409.16252).\n"
            "- License: CC-BY-4.0; Sentinel-2 © Copernicus/ESA.\n")


def write_collections(out_root):
    feat = Path(out_root) / "features"
    feat.mkdir(parents=True, exist_ok=True)
    (feat / "catalog.json").write_text(json.dumps(build_features_catalog(), indent=2) + "\n")
    print(f"wrote {feat}/catalog.json (sub-catalog grouping the per-year collections)")
    for year in (2024, 2025):
        d = feat / str(year)
        d.mkdir(parents=True, exist_ok=True)
        (d / "collection.json").write_text(json.dumps(build_collection(year), indent=2) + "\n")
        (d / "README.md").write_text(_readme(year))
        (d / "llms.txt").write_text(_llms(year))
        print(f"wrote {d}/collection.json (+ README, llms)")


# ── S3-only item + stac-geoparquet generation (run on rails) ──────────────────

def generate_items(year, workdir, limit=None, upload=True):
    """Per (tile, year): read COG header for proj, build item JSON, write to S3;
    accumulate a STAC-GeoParquet items.parquet and write it to S3. Outputs are
    NOT committed (the workdir should be gitignored)."""
    import duckdb, json as _json
    import rasterio
    con = duckdb.connect()
    con.execute("INSTALL spatial; LOAD spatial; INSTALL httpfs; LOAD httpfs; SET TimeZone='UTC';")
    q = (f"SELECT tile_id, ST_AsGeoJSON(ANY_VALUE(geometry)) g, "
         f"ST_XMin(ANY_VALUE(geometry)) xmin, ST_YMin(ANY_VALUE(geometry)) ymin, "
         f"ST_XMax(ANY_VALUE(geometry)) xmax, ST_YMax(ANY_VALUE(geometry)) ymax "
         f"FROM read_parquet('{INDEX_PARQUET}') WHERE EXTRACT(year FROM time)={year} "
         f"GROUP BY tile_id ORDER BY tile_id" + (f" LIMIT {limit}" if limit else ""))
    rows = con.execute(q).fetchall()
    d = Path(workdir) / "features" / str(year) / "items"; d.mkdir(parents=True, exist_ok=True)
    records = []
    for tile_id, g, xmin, ymin, xmax, ymax in rows:
        cog = f"{COG_BASE}/s2med_harvest/{tile_id}/{year}0101.tif"
        try:
            with rasterio.open(cog) as ds:
                proj_code = f"EPSG:{ds.crs.to_epsg()}"; shape = list(ds.shape)
                transform = list(ds.transform)[:6]
        except Exception as e:  # noqa: BLE001
            print(f"SKIP {tile_id}: cannot read COG ({e})"); continue
        item = build_item(tile_id, year, _json.loads(g), [xmin, ymin, xmax, ymax],
                          proj_code, shape, transform)
        (d / f"{item['id']}.json").write_text(_json.dumps(item))
        records.append(item)
    # STAC-GeoParquet (one row per item) via stac-geoparquet if available, else a simple parquet
    _write_stac_geoparquet(records, Path(workdir) / "features" / str(year) / "items.parquet")
    print(f"{year}: wrote {len(records)} items + items.parquet to {workdir}")
    if upload:
        base = f"s3://{S3_BUCKET}/{S3_PREFIX}/features/{year}"
        subprocess.run(["aws", "s3", "cp", str(d), f"{base}/items/", "--recursive",
                        "--quiet", "--region", "us-west-2", "--content-type", "application/geo+json"], check=True)
        subprocess.run(["aws", "s3", "cp", str(Path(workdir)/'features'/str(year)/'items.parquet'),
                        f"{base}/items.parquet", "--quiet", "--region", "us-west-2"], check=True)
        print(f"{year}: uploaded items/ + items.parquet to {base}")


def _write_stac_geoparquet(items, path):
    try:
        import stac_geoparquet, pyarrow.parquet as pq
        rb = stac_geoparquet.arrow.parse_stac_items_to_arrow(items)
        pq.write_table(stac_geoparquet.arrow.stac_table_to_items and __import__("pyarrow").Table.from_batches(list(rb)) or rb, str(path))
    except Exception:
        # fallback: minimal columns so the index still exists
        import pyarrow as pa, pyarrow.parquet as pq
        cols = {"id": [], "datetime": [], "bbox": [], "harvest_href": [], "planting_href": []}
        for it in items:
            cols["id"].append(it["id"]); cols["datetime"].append(it["properties"]["datetime"])
            cols["bbox"].append(json.dumps(it["bbox"]))
            cols["harvest_href"].append(it["assets"]["harvest"]["href"])
            cols["planting_href"].append(it["assets"]["planting"]["href"])
        pq.write_table(pa.table(cols), str(path))


def make_thumbnail(tile, year, workdir, upload=True):
    """Render a true-color (B04/B03/B02) preview of one tile's harvest composite to
    features/thumbnail.png (the collection thumbnail)."""
    import numpy as np
    import rasterio
    from rasterio.enums import Resampling
    from PIL import Image
    Path(workdir).mkdir(parents=True, exist_ok=True)
    out = Path(workdir) / "thumbnail.png"
    cog = f"{COG_BASE}/s2med_harvest/{tile}/{year}0101.tif"
    target = 600
    with rasterio.open(cog) as ds:
        scale = max(1, ds.width // target)
        w, h = ds.width // scale, ds.height // scale
        rgb = ds.read([3, 2, 1], out_shape=(3, h, w),
                      resampling=Resampling.average).astype("float32")  # R=B04, G=B03, B=B02
    arr = np.zeros((h, w, 3), dtype="uint8")
    for i in range(3):
        b = rgb[i]
        v = b[np.isfinite(b) & (b > 0)]
        if v.size:
            lo, hi = np.percentile(v, [2, 98])
            arr[..., i] = (np.clip((np.nan_to_num(b) - lo) / (hi - lo + 1e-6), 0, 1) * 255).astype("uint8")
    Image.fromarray(arr).save(out)
    print(f"wrote {out} ({w}x{h}) from harvest tile {tile} {year}")
    if upload:
        subprocess.run(["aws", "s3", "cp", str(out),
                        f"s3://{S3_BUCKET}/{S3_PREFIX}/features/thumbnail.png",
                        "--quiet", "--region", "us-west-2", "--content-type", "image/png"], check=True)
        print("uploaded features/thumbnail.png")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)
    c = sub.add_parser("collections"); c.add_argument(
        "--out", default=str(Path(__file__).resolve().parents[2] / "catalog"))
    it = sub.add_parser("items"); it.add_argument("year", type=int, choices=[2024, 2025])
    it.add_argument("--workdir", default=os.environ.get("WORK", "/tmp/ftw-features"))
    it.add_argument("--limit", type=int, default=None)
    it.add_argument("--no-upload", action="store_true")
    th = sub.add_parser("thumbnail"); th.add_argument("--tile", default="31UDP")
    th.add_argument("--year", type=int, default=2024)
    th.add_argument("--workdir", default=os.environ.get("WORK", "/tmp/ftw-features"))
    th.add_argument("--no-upload", action="store_true")
    args = ap.parse_args(argv)
    if args.cmd == "collections":
        write_collections(args.out)
    elif args.cmd == "thumbnail":
        make_thumbnail(args.tile, args.year, args.workdir, upload=not args.no_upload)
    else:
        generate_items(args.year, args.workdir, args.limit, upload=not args.no_upload)
    return 0


if __name__ == "__main__":
    sys.exit(main())
