#!/usr/bin/env python3
"""STAC for the FTW Sentinel-2 planting/harvest composites ("features").

Two collections, one per year (`s2-planting-harvest-composites-2024` / `-2025`).
Each collection (committed to the repo) carries the global Zarr mosaic as a
collection asset and a **STAC-GeoParquet** asset (the item index). The per-tile
items (harvest + planting COG assets), the grid catalogs and the items.parquet are
**S3-only** — generated by this script, written under `features/<year>/…` on S3, and
NEVER committed (they're .gitignore'd). At ~22.7k tiles/year that's the scalable
pattern.

The items are browsable as a two-level **MGRS tree** — collection -> UTM zone (60)
-> grid zone `35U` (~11 per zone) -> ~36 items:

    features/<year>/collection.json      committed here; children are the 60 zones
    features/<year>/35/catalog.json      "UTM Zone 35 - Dem. Rep. Congo, Sudan, ..."
    features/<year>/35/35u/catalog.json  "Zone 35U - Ukraine, Belarus, Lithuania, ..."
    features/<year>/35/35u/35uqa_<year>.json

Node titles come from mgrs_places.json (see the `places` subcommand). The parquet
remains the way to *query* the items; the tree is how you *browse* them.

Subcommands:
    build_features_items.py collections                 # write the 2 collection.json + README + llms (repo)
    build_features_items.py items 2024 [--limit N]      # generate the grid tree + items.parquet (S3); run on rails
    build_features_items.py items 2024 --from-parquet   # ... rebuilt from the published parquet (metadata-only; fast, anywhere)
    build_features_items.py places                      # rebuild mgrs_places.json (grid node titles)

Portolan 0.1: everything this script emits is spec-conformant — catalogs/collections
declare the v0.1.0 schema URI, structural links are relative with no `self`, each
carries AGENTS.md + rel:agents/describedby, Source Cooperative is the sole `host`
(last) so collections are "mirrors" (rel:via text/html + `updated`), and assets carry
the file extension. Per-item COG assets get `file:size` (via HTTP HEAD). **`file:checksum`
is deferred**: hashing ~90k COGs (~tens of TB) post-hoc is impractical, so per
PORTO-CORE-030 it should be stamped by the COG generation/upload pipeline, not here.
After re-running `collections`, re-run scripts/migrate/backfill_file_meta.py --local-only
to restore file:size/file:checksum on the in-repo assets (README/llms/thumbnail).
"""
from __future__ import annotations

import argparse
import datetime
import json
import os
import subprocess
import sys
import time
import urllib.request
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from pathlib import Path

PUB = "https://data.source.coop/ftw/global-data"
S3_BUCKET = "us-west-2.opendata.source.coop"
S3_PREFIX = "tge-labs/ftw-global-data"
COG_BASE = f"{PUB}/features/cogs/alpha"
ZARR_HREF = f"{PUB}/features/zarr/alpha/global.zarr"
# Read the COG index over public HTTPS (duckdb s3:// hits an SSL/virtual-host issue
# with the dotted Source Coop bucket name).
INDEX_PARQUET = f"{PUB}/features/cogs/alpha/index.parquet"
FTW_URL = "https://fieldsofthe.world"
FTW_BENCHMARK_DATA = "https://source.coop/kerner-lab/fields-of-the-world"

PORTOLAN_EXT = "https://schemas.portolan-sdi.org/portolan/v0.1.0/schema.json"
PROJ_EXT = "https://stac-extensions.github.io/projection/v2.0.0/schema.json"
EO_EXT = "https://stac-extensions.github.io/eo/v2.0.0/schema.json"
GRID_EXT = "https://stac-extensions.github.io/grid/v1.1.0/schema.json"
ITEM_ASSETS_EXT = "https://stac-extensions.github.io/item-assets/v1.0.0/schema.json"
SCI_EXT = "https://stac-extensions.github.io/scientific/v1.0.0/schema.json"
FILE_EXT = "https://stac-extensions.github.io/file/v2.1.0/schema.json"

# Portolan 0.1 providers: the dataset is self-published by Taylor Geospatial and
# served on Source Cooperative, which is the `host` (last); host != producer makes
# each collection a "mirror" (so it keeps a rel:via text/html + `updated`).
SOURCE_COOP_PROVIDER = {"name": "Source Cooperative", "roles": ["host"],
                        "url": "https://source.coop/ftw/global-data"}
FTW_PRODUCERS = [
    {"name": "Taylor Geospatial Institute", "roles": ["producer", "licensor", "processor"],
     "url": "https://taylorgeospatial.org/"},
    {"name": "Microsoft AI for Good Research Lab", "roles": ["producer", "processor"],
     "url": "https://www.microsoft.com/en-us/research/group/ai-for-good-research-lab/"},
    {"name": "European Space Agency / Copernicus", "roles": ["producer"],
     "url": "https://sentinels.copernicus.eu/", "description": "Sentinel-2 source imagery"},
]


def _now():
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _doc_links():
    """The rel:agents / rel:describedby markdown links every catalog+collection needs."""
    return [
        {"rel": "agents", "href": "./AGENTS.md", "type": "text/markdown",
         "title": "Guidance for AI agents"},
        {"rel": "describedby", "href": "./README.md", "type": "text/markdown",
         "title": "Human-readable documentation"},
    ]


def _agents_md(title):
    return (
        f"# AGENTS.md — {title}\n\n"
        "Guidance for AI agents and automated clients working with this Portolan/STAC object.\n\n"
        "- Part of the **Fields of the World — Global** catalog "
        "(`https://data.source.coop/ftw/global-data/`).\n"
        "- Data files (COG, Zarr) are hosted on Source Cooperative and referenced in place; "
        "this repo carries metadata only.\n"
        "- Prefer `llms.txt` for query snippets and `README.md` for human documentation.\n"
        "- Resolve assets and structural links relative to this object; there are no `self` links.\n"
    )

# Source Sentinel-2 imagery. derived_from -> the official ESA Copernicus Data Space
# Ecosystem STAC (Sentinel-2 L2A); via -> the AWS Open Data / Earth Search L2A COG
# catalog that indexes the `sentinel-cogs` bucket these composites were physically built from.
S2_MISSION = "https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-2"
S2_L2A_OFFICIAL = "https://stac.dataspace.copernicus.eu/v1/collections/sentinel-2-l2a"
S2_L2A_COGS = "https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a"

# The per-year COG collections + the Zarr collection live under one STAC sub-catalog,
# so the root shows a single "composites" entry that expands into the three.
FEAT_CATALOG_ID = "s2-planting-harvest-composites"
FEAT_CATALOG_TITLE = "FTW Global — Sentinel-2 Planting & Harvest Composites"
THUMB_HREF = f"{PUB}/features/thumbnail.png"
SRC = "https://source.coop/ftw/global-data"           # browsable Source Coop dirs (README links)
PREDICTIONS_DIR = f"{SRC}/predictions"
DATACUBE_EXT = "https://stac-extensions.github.io/datacube/v2.2.0/schema.json"
ZARR_ID = "s2-planting-harvest-composites-zarr"
ZARR_TITLE = "FTW Global — Sentinel-2 Planting & Harvest Composites — Zarr mosaic (2024 & 2025)"
ZARR_COLL_HREF = f"{PUB}/features/zarr/collection.json"


def cog_title(year):
    return f"FTW Global — Sentinel-2 Planting & Harvest Composites — COGs ({year})"

SPECTRAL_BANDS = [
    {"name": "B02", "eo:common_name": "blue", "eo:center_wavelength": 0.49},
    {"name": "B03", "eo:common_name": "green", "eo:center_wavelength": 0.56},
    {"name": "B04", "eo:common_name": "red", "eo:center_wavelength": 0.665},
    {"name": "B08", "eo:common_name": "nir", "eo:center_wavelength": 0.842},
    {"name": "N_VALID_PIXELS",
     "description": "Count of valid Sentinel-2 scenes after quality-flag masking (not a reflectance band)."},
]
SCI_PUBLICATIONS = [
    {"doi": "10.48550/arXiv.2409.16252",
     "citation": "Kerner, H. et al. (2025). Fields of the World: A Machine Learning Benchmark "
                 "Dataset for Global Agricultural Field Boundary Segmentation. AAAI-2025. arXiv:2409.16252."},
    {"doi": "10.48550/arXiv.2603.27101",
     "citation": "Muhawenayo, G. et al. (2026). PRUE: A Practical Recipe for Field Boundary "
                 "Segmentation at Scale. arXiv:2603.27101."},
    {"doi": "10.48550/arXiv.2602.08131",
     "citation": "Corley, I. et al. (2026). Fields of The World: A Field Guide for Extracting "
                 "Agricultural Field Boundaries. arXiv:2602.08131."},
]
_DESC = (
    "Sentinel-2 **planting- and harvest-season median composites** at 10 m — the model-input "
    "features for the FTW Global field-boundary predictions. For each grid tile and season, "
    "~5–10 quality-masked Sentinel-2 scenes (selected by latitude-based day-of-year heuristics) "
    "are reduced to a per-pixel median; bands are B02/B03/B04/B08 plus N_VALID_PIXELS, in the "
    "tile's native UTM zone. Part of [Fields of the World]({ftw}). These composites feed the "
    "**PRUE** U-Net model ([Muhawenayo et al. 2026](https://arxiv.org/abs/2603.27101); 76% IoU / "
    "47% object-F1 on the [Fields of the World benchmark]({bench}) of 70,462 Sentinel-2 samples "
    "across 24 countries, [Kerner et al. 2025](https://arxiv.org/abs/2409.16252)), whose outputs "
    "are the [field-boundary predictions](https://source.coop/ftw/global-data/predictions). The "
    "same composites are published in two equivalent formats: per-tile **COGs** (these per-year "
    "collections) and a single global EPSG:4326 **[Zarr mosaic](https://source.coop/ftw/global-data/features/zarr)** "
    "(its own collection), stackable with the prediction Zarr.\n\n"
    "**Items & index:** ~22.7k per-tile items (each with a `planting` and `harvest` COG asset). "
    "Browse them through the **MGRS grid**: each per-year collection's children are the 60 UTM "
    "zones, each "
    "expanding into its grid-zone cells (`35U`, ~36 tiles each) and then the tiles themselves. To "
    "*query* rather than browse, use the collection's STAC-GeoParquet asset (`items.parquet`), "
    "which lists every item for the year in one file."
).format(ftw=FTW_URL, bench=FTW_BENCHMARK_DATA)


def collection_id(year):
    return f"s2-planting-harvest-composites-{year}"


def build_collection(year):
    base = f"{PUB}/features/{year}"
    places = load_places()
    # Browse children: one catalog per UTM zone, each expanding into its MGRS band cells
    # and then ~36 items. Structural links MUST be relative (PTL-LNK-004), and they resolve
    # in the *published* catalog — but the tree itself is generated to S3 by `items <year>`
    # and is not in this repo, so these targets are absent from a git checkout (see the
    # generated-tree exemption in tests/test_links.py).
    zone_children = [
        {"rel": "child", "href": f"./{z}/catalog.json", "type": "application/json",
         "title": zone_title(z, places, year)}
        for z in sorted(places.get("zones", {}))
    ]
    asset_band_common = {"gsd": 10, "data_type": "float32", "bands": SPECTRAL_BANDS}
    return {
        "type": "Collection",
        "stac_version": "1.1.0",
        "stac_extensions": [PORTOLAN_EXT, PROJ_EXT, EO_EXT, ITEM_ASSETS_EXT, SCI_EXT, FILE_EXT],
        "id": collection_id(year),
        "title": cog_title(year),
        "description": _DESC,
        "license": "CC-BY-4.0",
        "updated": _now(),
        "keywords": ["Sentinel-2", "median composite", "agriculture", "field boundaries",
                     "Fields of the World", "FTW", "model input", "features", "10m", str(year)],
        "providers": [*FTW_PRODUCERS, dict(SOURCE_COOP_PROVIDER)],
        "extent": {
            "spatial": {"bbox": [[-180.0, -57.830146, 180.0, 83.748345]]},
            "temporal": {"interval": [[f"{year}-01-01T00:00:00Z", f"{year}-12-31T23:59:59Z"]]},
        },
        "summaries": {"gsd": [10], "eo:bands": SPECTRAL_BANDS},
        "item_assets": {
            "planting": {"type": "image/tiff; application=geotiff; profile=cloud-optimized",
                         "title": "Planting-season Sentinel-2 median composite",
                         "roles": ["data"], **asset_band_common},
            "harvest": {"type": "image/tiff; application=geotiff; profile=cloud-optimized",
                        "title": "Harvest-season Sentinel-2 median composite",
                        "roles": ["data"], **asset_band_common},
        },
        "sci:publications": SCI_PUBLICATIONS,
        "assets": {
            "thumbnail": {"href": THUMB_HREF, "type": "image/png",
                          "title": "Sentinel-2 composite preview",
                          "roles": ["thumbnail", "overview"]},
            "geoparquet-items": {"href": f"{base}/items.parquet",
                                 "type": "application/vnd.apache.parquet",
                                 "title": "STAC-GeoParquet item index (per-tile items)",
                                 "description": "STAC-GeoParquet listing all per-tile items for this "
                                                "year; the scalable item index in lieu of item links.",
                                 "roles": ["collection-mirror"]},
            "documentation": {"href": "./llms.txt", "type": "text/markdown",
                              "title": "Agent/LLM usage guide", "roles": ["documentation"]},
            "README": {"href": "./README.md", "type": "text/markdown",
                       "title": "Human-readable README", "roles": ["metadata"]},
        },
        "links": [
            {"rel": "root", "href": "../../catalog.json", "type": "application/json",
             "title": "Fields of the World — Global"},
            {"rel": "parent", "href": "../catalog.json", "type": "application/json",
             "title": FEAT_CATALOG_TITLE},
            {"rel": "license", "href": "https://creativecommons.org/licenses/by/4.0/",
             "type": "text/html", "title": "CC-BY-4.0"},
            {"rel": "cite-as", "href": "https://aka.ms/ftw-global-paper", "title": "FTW Global paper"},
            # Mirror provenance: a text/html rel:via to the original source (PTL-PRO-001).
            {"rel": "via", "href": FTW_BENCHMARK_DATA, "type": "text/html",
             "title": "Fields of the World benchmark (training data) on Source Cooperative"},
            {"rel": "derived_from", "href": S2_L2A_OFFICIAL, "type": "application/json",
             "title": "Sentinel-2 L2A — Copernicus Data Space Ecosystem (ESA, official)"},
            # non-html source ref uses rel:related (a rel:via must be text/html)
            {"rel": "related", "href": S2_L2A_COGS, "type": "application/json",
             "title": "Sentinel-2 L2A COGs (AWS Open Data / Earth Search — source scenes used)"},
            {"rel": "related", "href": ZARR_COLL_HREF, "type": "application/json",
             "title": "Same composites as a global Zarr mosaic"},
            {"rel": "related", "href": f"{PUB}/predictions/zarr/collection.json",
             "type": "application/json", "title": "Prediction probabilities (Zarr) made from these features"},
            *zone_children,
            {"rel": "llms", "href": "./llms.txt", "type": "text/markdown",
             "title": "Agent/LLM usage guide"},
            *_doc_links(),
        ],
    }


def build_zarr_collection():
    """The Sentinel-2 composites as a single global EPSG:4326 Zarr mosaic — the same data
    as the per-year COG collections, in a different (datacube) format."""
    return {
        "type": "Collection",
        "stac_version": "1.1.0",
        "stac_extensions": [PORTOLAN_EXT, DATACUBE_EXT, SCI_EXT, FILE_EXT],
        "id": ZARR_ID,
        "title": ZARR_TITLE,
        "updated": _now(),
        "description": (
            "The FTW Sentinel-2 planting/harvest median composites as a single global **Zarr "
            "mosaic** (Zarr V3, EPSG:4326, ~10 m), with a `time` dimension covering 2024 and "
            "2025. **This is the same data as the per-tile COG collections** "
            "([COGs 2024](https://source.coop/ftw/global-data/features/2024), "
            "[COGs 2025](https://source.coop/ftw/global-data/features/2025)) — choose COGs for "
            "tile/window access, or this Zarr for analysis-ready, chunked array access stackable "
            "with the [prediction Zarr](https://source.coop/ftw/global-data/predictions/zarr). "
            "Bands B02/B03/B04/B08 + N_VALID_PIXELS; the model-input features for the "
            "[field-boundary predictions](https://source.coop/ftw/global-data/predictions). "
            "Note: a GeoZarr that does not yet implement multiscales, so it is not yet directly "
            "web-tileable (in progress)."),
        "license": "CC-BY-4.0",
        "keywords": ["Sentinel-2", "median composite", "agriculture", "field boundaries",
                     "Fields of the World", "FTW", "features", "Zarr", "GeoZarr", "datacube", "10m"],
        "providers": [*FTW_PRODUCERS, dict(SOURCE_COOP_PROVIDER)],
        "extent": {
            "spatial": {"bbox": [[-180.0, -57.830146, 180.0, 83.748345]]},
            "temporal": {"interval": [["2024-01-01T00:00:00Z", "2025-12-31T23:59:59Z"]]},
        },
        "cube:dimensions": {
            "time": {"type": "temporal", "extent": ["2024-01-01T00:00:00Z", "2025-12-31T23:59:59Z"]},
            "x": {"type": "spatial", "axis": "x", "extent": [-180.0, 180.0], "reference_system": 4326},
            "y": {"type": "spatial", "axis": "y", "extent": [-57.830146, 83.748345], "reference_system": 4326},
        },
        "summaries": {"gsd": [10]},
        "sci:publications": SCI_PUBLICATIONS,
        "assets": {
            "thumbnail": {"href": THUMB_HREF, "type": "image/png",
                          "title": "Sentinel-2 composite preview",
                          "roles": ["thumbnail", "overview"]},
            "data": {"href": ZARR_HREF, "type": "application/vnd.zarr; version=3",
                     "title": "Global Sentinel-2 composite mosaic (Zarr V3, EPSG:4326, ~10 m)",
                     "description": "Dims (time, band, y, x). "
                                    "Open with xarray: xr.open_zarr(href).pipe(rasterix.assign_index).",
                     "roles": ["data", "cloud-optimized"]},
            "documentation": {"href": "./llms.txt", "type": "text/markdown",
                              "title": "Agent/LLM usage guide", "roles": ["documentation"]},
            "README": {"href": "./README.md", "type": "text/markdown",
                       "title": "Human-readable README", "roles": ["metadata"]},
        },
        "links": [
            {"rel": "root", "href": "../../catalog.json", "type": "application/json",
             "title": "Fields of the World — Global"},
            {"rel": "parent", "href": "../catalog.json", "type": "application/json",
             "title": FEAT_CATALOG_TITLE},
            {"rel": "license", "href": "https://creativecommons.org/licenses/by/4.0/",
             "type": "text/html", "title": "CC-BY-4.0"},
            {"rel": "cite-as", "href": "https://aka.ms/ftw-global-paper", "title": "FTW Global paper"},
            # Mirror provenance: a text/html rel:via to the original source (PTL-PRO-001).
            {"rel": "via", "href": FTW_BENCHMARK_DATA, "type": "text/html",
             "title": "Fields of the World benchmark (training data) on Source Cooperative"},
            {"rel": "related", "href": f"{PUB}/features/2024/collection.json",
             "type": "application/json", "title": "Same composites as per-tile COGs (2024)"},
            {"rel": "related", "href": f"{PUB}/features/2025/collection.json",
             "type": "application/json", "title": "Same composites as per-tile COGs (2025)"},
            {"rel": "related", "href": f"{PUB}/predictions/zarr/collection.json",
             "type": "application/json", "title": "Prediction probabilities (Zarr) made from these features"},
            {"rel": "derived_from", "href": S2_L2A_OFFICIAL, "type": "application/json",
             "title": "Sentinel-2 L2A — Copernicus Data Space Ecosystem (ESA, official)"},
            {"rel": "llms", "href": "./llms.txt", "type": "text/markdown",
             "title": "Agent/LLM usage guide"},
            *_doc_links(),
        ],
    }


def build_features_catalog():
    """A STAC Catalog grouping the per-year composite collections, so the root shows
    one 'composites' entry that expands into 2024 / 2025."""
    return {
        "type": "Catalog",
        "stac_version": "1.1.0",
        "stac_extensions": [PORTOLAN_EXT],
        "id": FEAT_CATALOG_ID,
        "title": FEAT_CATALOG_TITLE,
        "description": (
            "Sentinel-2 planting- and harvest-season median composites (10 m) — the model-"
            "input features for the FTW Global [field-boundary predictions](https://source.coop/ftw/global-data/predictions). "
            "The same composites in two formats: per-tile **COGs** (one collection per year, 2024 "
            "& 2025) and a single global **Zarr mosaic**. See each collection for assets and "
            "access snippets."),
        "updated": _now(),
        # NOTE: STAC Catalogs must NOT carry `assets` — stac-js doesn't wrap catalog
        # assets as Asset objects, so a catalog thumbnail asset crashes the browser
        # (`asset.hasRole is not a function`). The card thumbnail comes from the
        # rel="preview" link below, which stac-js's getThumbnails uses for catalogs.
        "links": [
            {"rel": "root", "href": "../catalog.json", "type": "application/json",
             "title": "Fields of the World — Global"},
            {"rel": "parent", "href": "../catalog.json", "type": "application/json",
             "title": "Fields of the World — Global"},
            {"rel": "preview", "href": THUMB_HREF, "type": "image/png",
             "title": "Sentinel-2 composite preview"},
            {"rel": "child", "href": "./2024/collection.json", "type": "application/json",
             "title": cog_title(2024)},
            {"rel": "child", "href": "./2025/collection.json", "type": "application/json",
             "title": cog_title(2025)},
            {"rel": "child", "href": "./zarr/collection.json", "type": "application/json",
             "title": ZARR_TITLE},
            *_doc_links(),
        ],
    }


def build_item(tile_id, year, geometry, bbox, proj_code, proj_shape, proj_transform, sizes=None):
    iid = f"{tile_id.lower()}_{year}"
    sizes = sizes or {}
    def asset(ds, season, key):
        a = {
            "href": f"{COG_BASE}/{ds}/{tile_id}/{year}0101.tif",
            "type": "image/tiff; application=geotiff; profile=cloud-optimized",
            "title": f"{season}-season Sentinel-2 median composite",
            "description": (f"Per-pixel median of ~5–10 quality-masked Sentinel-2 scenes over the "
                            f"{season.lower()} day-of-year window; 10 m, bands B02/B03/B04/B08 + N_VALID_PIXELS."),
            "roles": ["data"], "gsd": 10, "data_type": "float32", "bands": SPECTRAL_BANDS,
        }
        # Portolan 0.1 requires file:size + file:checksum. file:size is cheap (HTTP HEAD).
        # file:checksum (multihash of the full COG) is DEFERRED — hashing ~90k COGs (~tens of
        # TB) post-hoc is impractical; per PORTO-CORE-030 it should be stamped by the COG
        # generation/upload pipeline. See module docstring.
        if sizes.get(key) is not None:
            a["file:size"] = sizes[key]
        return a
    return {
        "type": "Feature", "stac_version": "1.1.0",
        "stac_extensions": [PROJ_EXT, EO_EXT, GRID_EXT, FILE_EXT],
        "id": iid, "geometry": geometry, "bbox": bbox,
        "properties": {
            "title": f"Sentinel-2 planting & harvest composites — tile {tile_id} ({year})",
            "description": (
                f"[Sentinel-2]({S2_MISSION}) planting- and harvest-season **median composites** for "
                f"MGRS tile `{tile_id}`, {year}, at 10 m — the model-input *features* for the "
                f"[Fields of the World]({FTW_URL}) global field-boundary predictions. Each composite is "
                "the per-pixel median of ~5–10 quality-masked (SCL cloud/shadow) Sentinel-2 L2A scenes "
                "selected by planting/harvest day-of-year heuristics; bands B02/B03/B04/B08 + "
                f"N_VALID_PIXELS, in the tile's native UTM zone. Derived from "
                f"[Sentinel-2 L2A]({S2_L2A_OFFICIAL}) (ESA / Copernicus). These features feed the "
                f"[PRUE](https://arxiv.org/abs/2603.27101) model whose outputs are the FTW "
                f"[predictions]({PUB}/predictions/vectors/collection.json)."),
            "datetime": f"{year}-07-01T00:00:00Z",
            "start_datetime": f"{year}-01-01T00:00:00Z",
            "end_datetime": f"{year}-12-31T23:59:59Z",
            "gsd": 10, "grid:code": f"MGRS-{tile_id}",
            "proj:code": proj_code, "proj:shape": proj_shape, "proj:transform": proj_transform,
        },
        "collection": collection_id(year),
        "assets": {"planting": asset("s2med_planting", "Planting", "planting"),
                   "harvest": asset("s2med_harvest", "Harvest", "harvest")},
        # Structural links MUST be relative and there is no self link. The item lives at
        # features/<year>/<zone>/<gzd>/<iid>.json (the MGRS browse grid), so root is four
        # levels up, the collection two, and the parent is the GZD catalog beside it.
        "links": [
            {"rel": "root", "href": "../../../../catalog.json", "type": "application/json",
             "title": "Fields of the World — Global"},
            {"rel": "collection", "href": "../../collection.json", "type": "application/json",
             "title": f"FTW Global — Sentinel-2 Planting & Harvest Composites ({year})"},
            {"rel": "parent", "href": "./catalog.json", "type": "application/json",
             "title": f"MGRS grid zone {tile_id[:3].upper()} ({year})"},
            {"rel": "derived_from", "href": S2_L2A_OFFICIAL, "type": "application/json",
             "title": "Sentinel-2 L2A — Copernicus Data Space Ecosystem (ESA, official)"},
            {"rel": "related", "href": S2_L2A_COGS, "type": "application/json",
             "title": "Sentinel-2 L2A COGs (AWS Open Data / Earth Search — source scenes used)"},
        ],
    }


def _readme(year):
    return (f"# {cog_title(year)}\n\n"
            f'<img src="{THUMB_HREF}" width="600" alt="Sentinel-2 composite preview">\n\n'
            + _DESC.replace("\\n", "\n") + "\n\n"
            "## Access (COGs)\n\n"
            "Per-tile COGs are indexed by the STAC-GeoParquet item index "
            f"(`{PUB}/features/{year}/items.parquet`); each item has a `planting` and a `harvest` "
            "5-band COG (B02/B03/B04/B08/N_VALID_PIXELS) in its native UTM zone. The **same data** "
            f"is also published as a global [Zarr mosaic]({SRC}/features/zarr), and these composites "
            f"are the model inputs for the [field-boundary predictions]({PREDICTIONS_DIR}).\n\n"
            "## License\n\nCC-BY-4.0. Sentinel-2 imagery © Copernicus/ESA; composites by the "
            "Taylor Geospatial Institute and Microsoft AI for Good Research Lab.\n")


def _llms(year):
    return (f"# FTW Global — Sentinel-2 Planting & Harvest Composites ({year})\n\n"
            "Sentinel-2 planting/harvest median composites (10 m) — the model-input features for the "
            "FTW field-boundary predictions. Part of Fields of the World.\n\n"
            f"- Global Zarr mosaic: {ZARR_HREF} (xr.open_zarr; EPSG:4326, dims time,band,y,x)\n"
            f"- Per-tile COG items indexed by STAC-GeoParquet: {PUB}/features/{year}/items.parquet\n"
            f"- Or browse them: collection -> UTM zone -> MGRS grid zone -> item, e.g. "
            f"{PUB}/features/{year}/35/35u/catalog.json (~36 tiles per cell)\n"
            "- Each tile item: `planting` + `harvest` COGs, bands B02/B03/B04/B08 + N_VALID_PIXELS, "
            "native UTM, 10 m.\n"
            "- Composites feed the PRUE U-Net model (arXiv:2603.27101) trained on the FTW benchmark "
            f"(data: {FTW_BENCHMARK_DATA}; arXiv:2409.16252).\n"
            "- License: CC-BY-4.0; Sentinel-2 © Copernicus/ESA.\n")


def _features_catalog_readme():
    return (
        f"# {FEAT_CATALOG_TITLE}\n\n"
        f'<img src="{THUMB_HREF}" width="600" alt="Sentinel-2 composite preview">\n\n'
        + _DESC.replace("\\n", "\n") + "\n\n"
        "## Collections\n\n"
        f"- [**COGs — 2024**]({SRC}/features/2024) — per-tile planting + harvest COGs + a STAC-GeoParquet item index.\n"
        f"- [**COGs — 2025**]({SRC}/features/2025)\n"
        f"- [**Zarr mosaic (2024 & 2025)**]({SRC}/features/zarr) — the same composites as one global datacube.\n\n"
        "## Folder layout\n\n"
        "- `cogs/` — the actual per-tile **COG** files (GeoTIFF) plus their `index.parquet`.\n"
        "- `zarr/alpha/global.zarr` — the global **Zarr** mosaic data.\n"
        "- `2024/`, `2025/`, `zarr/` — the **STAC metadata** (a `collection.json`, `README.md`, "
        "item index). The `2024/` and `2025/` folders hold metadata only — the imagery itself "
        "lives under `cogs/` (and `zarr/`).\n\n"
        "Source imagery: [Sentinel-2 L2A](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-2) "
        "(ESA / Copernicus). License: CC-BY-4.0.\n")


def _zarr_readme():
    return (f"# {ZARR_TITLE}\n\n"
            f'<img src="{THUMB_HREF}" width="600" alt="Sentinel-2 composite preview">\n\n'
            "The FTW Sentinel-2 planting/harvest composites as a single global EPSG:4326 **Zarr "
            "mosaic** (Zarr V3, ~10 m), with a `time` dimension over 2024 & 2025 — the **same data** "
            f"as the per-tile COG collections ([COGs 2024]({SRC}/features/2024), "
            f"[COGs 2025]({SRC}/features/2025)), in datacube form. Bands B02/B03/B04/B08 + "
            f"N_VALID_PIXELS; the model-input features for the FTW "
            f"[field-boundary predictions]({PREDICTIONS_DIR}).\n\n"
            "## Access\n\n"
            "```python\nimport xarray as xr, rasterix\n"
            f"ds = xr.open_zarr(\"{ZARR_HREF}\").pipe(rasterix.assign_index)\n"
            "```\n\n"
            "This is a GeoZarr that does not yet implement multiscales, so it is not yet directly "
            "web-tileable (work in progress).\n\n"
            "## License\n\nCC-BY-4.0. Sentinel-2 imagery © Copernicus/ESA; composites by the "
            "Taylor Geospatial Institute and Microsoft AI for Good Research Lab.\n")


def _zarr_llms():
    return (f"# {ZARR_TITLE}\n\n"
            "Global Sentinel-2 planting/harvest composite mosaic (Zarr V3, EPSG:4326, ~10 m) — the "
            "same data as the per-tile COG collections, in datacube form. Part of Fields of the World.\n\n"
            f"- Zarr: {ZARR_HREF} (xr.open_zarr; dims time,band,y,x; time = 2024 & 2025)\n"
            f"- Equivalent COGs: {SRC}/features/2024 and {SRC}/features/2025\n"
            "- Bands: B02/B03/B04/B08 + N_VALID_PIXELS.\n"
            f"- Model-input features for the predictions: {PREDICTIONS_DIR}\n"
            "- GeoZarr; multiscales not yet implemented (not yet web-tileable).\n"
            "- License: CC-BY-4.0; Sentinel-2 © Copernicus/ESA.\n")


def write_collections(out_root):
    feat = Path(out_root) / "features"
    feat.mkdir(parents=True, exist_ok=True)
    (feat / "catalog.json").write_text(json.dumps(build_features_catalog(), indent=2) + "\n")
    (feat / "README.md").write_text(_features_catalog_readme())
    (feat / "AGENTS.md").write_text(_agents_md(FEAT_CATALOG_TITLE))
    print(f"wrote {feat}/catalog.json (+ README, AGENTS) — sub-catalog grouping the COG + Zarr collections")
    for year in (2024, 2025):
        d = feat / str(year)
        d.mkdir(parents=True, exist_ok=True)
        (d / "collection.json").write_text(json.dumps(build_collection(year), indent=2) + "\n")
        (d / "README.md").write_text(_readme(year))
        (d / "llms.txt").write_text(_llms(year))
        (d / "AGENTS.md").write_text(_agents_md(cog_title(year)))
        print(f"wrote {d}/collection.json (+ README, llms, AGENTS)")
    z = feat / "zarr"
    z.mkdir(parents=True, exist_ok=True)
    (z / "collection.json").write_text(json.dumps(build_zarr_collection(), indent=2) + "\n")
    (z / "README.md").write_text(_zarr_readme())
    (z / "llms.txt").write_text(_zarr_llms())
    (z / "AGENTS.md").write_text(_agents_md(ZARR_TITLE))
    print(f"wrote {z}/collection.json (+ README, llms, AGENTS) — Zarr mosaic collection")


# ── MGRS browse grid: place labels ───────────────────────────────────

# The per-tile items are browsable as a two-level MGRS tree (UTM zone -> zone+band
# "GZD" -> items). The grid is derivable from the tile id alone, but "35U" means
# nothing to a human, so each node is titled with the countries its tiles fall in.
# That lookup is precomputed once (`places` subcommand, needs duckdb+spatial and
# network) into mgrs_places.json and committed, so neither `collections` nor the
# rails `items` run needs Natural Earth or a spatial join.
PLACES_PATH = Path(__file__).resolve().parent / "mgrs_places.json"
NE_COUNTRIES_URL = ("https://raw.githubusercontent.com/nvkelso/natural-earth-vector/"
                    "master/geojson/ne_50m_admin_0_countries.geojson")
PLACES_TOP_N = 4          # countries named in a title before "(+N more)"


def load_places():
    try:
        return json.loads(PLACES_PATH.read_text())
    except FileNotFoundError:
        print(f"WARNING: {PLACES_PATH.name} missing - grid catalogs get bare MGRS titles "
              f"(run `build_features_items.py places` to generate it)", file=sys.stderr)
        return {"zones": {}, "gzds": {}}


def _fmt_lat(v):
    return f"{abs(v):.0f}°{'N' if v >= 0 else 'S'}"


def _fmt_lon(v):
    return f"{abs(v):.0f}°{'E' if v >= 0 else 'W'}"


def _place_phrase(entry):
    """'Poland, Ukraine, Belarus (+2 more)' - or an offshore lat/lon phrase."""
    if not entry:
        return ""
    names = entry.get("countries") or []
    if names:
        more = entry.get("more") or 0
        return ", ".join(names) + (f" (+{more} more)" if more else "")
    b = entry.get("bbox")
    if not b:
        return ""
    return (f"offshore, {_fmt_lat(b[1])}–{_fmt_lat(b[3])} / "
            f"{_fmt_lon(b[0])}–{_fmt_lon(b[2])}")


def zone_title(zone, places, year=None):
    where = _place_phrase(places.get("zones", {}).get(zone))
    t = f"UTM Zone {int(zone)}" + (f" — {where}" if where else "")
    return f"{t} ({year})" if year else t


def gzd_title(gzd, places, year=None):
    where = _place_phrase(places.get("gzds", {}).get(gzd))
    t = f"Zone {gzd.upper()}" + (f" — {where}" if where else "")
    return f"{t} ({year})" if year else t


def build_places(workdir, top=PLACES_TOP_N):
    """Rebuild mgrs_places.json: for every UTM zone and GZD, the countries its tiles
    actually fall in, ranked by how many tiles each contains (so the label reflects
    where the data is, not which country is biggest). Coastal/offshore tiles match no
    country - a node with none falls back to a lat/lon phrase."""
    import duckdb
    wd = Path(workdir); wd.mkdir(parents=True, exist_ok=True)
    ne = wd / "ne_50m_admin_0_countries.geojson"
    if not ne.exists():
        print(f"downloading Natural Earth 50m admin-0 -> {ne}")
        urllib.request.urlretrieve(NE_COUNTRIES_URL, ne)  # noqa: S310 - trusted host
    con = duckdb.connect()
    con.execute("INSTALL spatial; LOAD spatial; INSTALL httpfs; LOAD httpfs;")
    con.execute(f"create table cty as select NAME as name, geom from ST_Read('{ne}')")
    srcs = ", ".join(f"'{PUB}/features/{y}/items.parquet'" for y in (2024, 2025))
    con.execute(f"""create table t as select distinct
        upper(replace("grid:code", 'MGRS-', '')) as tile,
        bbox.xmin as xmin, bbox.ymin as ymin, bbox.xmax as xmax, bbox.ymax as ymax
        from read_parquet([{srcs}])""")
    n_tiles = con.execute("select count(*) from t").fetchone()[0]
    con.execute("""create table j as select t.tile, cty.name
        from t join cty on ST_Intersects(
            ST_MakeEnvelope(t.xmin, t.ymin, t.xmax, t.ymax), cty.geom)""")
    out = {}
    for key, expr in (("zones", "substr(tile,1,2)"), ("gzds", "lower(substr(tile,1,3))")):
        ranked = con.execute(f"""select {expr} as k, name, count(*) as n
            from j group by 1, 2 order by k, n desc, name""").fetchall()
        bboxes = con.execute(f"""select {expr} as k, min(xmin), min(ymin), max(xmax), max(ymax),
            count(*) from t group by 1 order by 1""").fetchall()
        by_key = {}
        for k, name, n in ranked:
            by_key.setdefault(k, []).append(name)
        out[key] = {}
        for k, xmin, ymin, xmax, ymax, n in bboxes:
            names = by_key.get(k, [])
            e = {"countries": names[:top], "tiles": n,
                 "bbox": [round(v, 4) for v in (xmin, ymin, xmax, ymax)]}
            if len(names) > top:
                e["more"] = len(names) - top
            out[key][k] = e
    PLACES_PATH.write_text(json.dumps(out, indent=1, ensure_ascii=False, sort_keys=True) + "\n")
    named = sum(1 for e in out["gzds"].values() if e["countries"])
    print(f"wrote {PLACES_PATH} from {n_tiles} tiles: {len(out['zones'])} zones, "
          f"{len(out['gzds'])} GZDs ({named} with country names, "
          f"{len(out['gzds']) - named} offshore-only)")


# ── MGRS browse grid: catalogs ───────────────────────────────────────

def grid_catalog_id(year, code):
    return f"{collection_id(year)}-{code.lower()}"


def _grid_desc(year, what, n_items, n_children=None):
    kids = f"{n_children} band cells covering " if n_children else ""
    return (f"{what} of the {year} Sentinel-2 planting/harvest composite tiles — {kids}"
            f"{n_items} tiles, each a STAC item with a `planting` and a `harvest` COG. "
            "Browse structure only: the tiles are also indexed in the collection's "
            f"STAC-GeoParquet ([items.parquet]({PUB}/features/{year}/items.parquet)), which is "
            "the better entry point for querying by geometry, country or date.")


def build_zone_catalog(year, zone, gzds, counts, places):
    """features/<year>/<zone>/catalog.json — one UTM zone, children are its GZD cells."""
    n = sum(counts[g] for g in gzds)
    return {
        "type": "Catalog", "stac_version": "1.1.0", "stac_extensions": [PORTOLAN_EXT],
        "id": grid_catalog_id(year, zone),
        "title": zone_title(zone, places, year),
        "description": _grid_desc(year, f"MGRS UTM zone {int(zone)}", n, len(gzds)),
        "updated": _now(),
        "links": [
            {"rel": "root", "href": "../../../catalog.json", "type": "application/json",
             "title": "Fields of the World — Global"},
            {"rel": "parent", "href": "../collection.json", "type": "application/json",
             "title": cog_title(year)},
            {"rel": "preview", "href": THUMB_HREF, "type": "image/png",
             "title": "Sentinel-2 composite preview"},
            *[{"rel": "child", "href": f"./{g}/catalog.json", "type": "application/json",
               "title": gzd_title(g, places)} for g in gzds],
            {"rel": "describedby", "href": "../README.md", "type": "text/markdown",
             "title": "Human-readable documentation"},
        ],
    }


def build_gzd_catalog(year, gzd, item_ids, places):
    """features/<year>/<zone>/<gzd>/catalog.json — one MGRS grid-zone cell, children are items."""
    return {
        "type": "Catalog", "stac_version": "1.1.0", "stac_extensions": [PORTOLAN_EXT],
        "id": grid_catalog_id(year, gzd),
        "title": gzd_title(gzd, places, year),
        "description": _grid_desc(year, f"MGRS grid zone {gzd.upper()}", len(item_ids)),
        "updated": _now(),
        "links": [
            {"rel": "root", "href": "../../../../catalog.json", "type": "application/json",
             "title": "Fields of the World — Global"},
            {"rel": "parent", "href": "../catalog.json", "type": "application/json",
             "title": zone_title(gzd[:2], places, year)},
            {"rel": "preview", "href": THUMB_HREF, "type": "image/png",
             "title": "Sentinel-2 composite preview"},
            *[{"rel": "item", "href": f"./{i}.json", "type": "application/geo+json",
               "title": f"Tile {i[:5].upper()} ({year})"} for i in item_ids],
            {"rel": "describedby", "href": "../../README.md", "type": "text/markdown",
             "title": "Human-readable documentation"},
        ],
    }


# ── S3-only item + stac-geoparquet generation (run on rails) ──────────────────

def _head_size(url, tries=3):
    """Byte size of a remote asset via HTTP HEAD (Content-Length), or None.

    Retried: a handful of HEADs per thousand fail transiently, and file:size is
    a Portolan MUST — a miss silently drops the field from that asset.
    """
    for attempt in range(tries):
        try:
            req = urllib.request.Request(url, method="HEAD", headers={"User-Agent": "ftw-features"})
            with urllib.request.urlopen(req, timeout=60) as r:  # noqa: S310 - trusted host
                cl = r.headers.get("Content-Length")
                return int(cl) if cl else None
        except Exception:  # noqa: BLE001
            if attempt == tries - 1:
                return None
            time.sleep(2 ** attempt)


def _probe_proj(task):
    """(tile_id, year) -> (tile_id, proj:code, proj:shape, proj:transform), or None.

    Runs in a worker *process*, not a thread: GDAL serialises /vsicurl behind a
    process-global lock, so threads measure ~1.5 s/tile at any pool size (worse
    than the ~1.2 s serial), while processes hit ~90 ms/tile.
    """
    import rasterio
    tile_id, year = task
    cog = f"{COG_BASE}/s2med_harvest/{tile_id}/{year}0101.tif"
    try:
        with rasterio.open(cog) as ds:
            return tile_id, f"EPSG:{ds.crs.to_epsg()}", list(ds.shape), list(ds.transform)[:6]
    except Exception as e:  # noqa: BLE001
        print(f"SKIP {tile_id}: cannot read COG ({e})")
        return None


def _records_from_published_parquet(year, limit=None):
    """Rebuild this year's items from the *published* items.parquet instead of re-reading
    ~45k COG headers and HEADing ~45k assets.

    Everything build_item needs — geometry, bbox, proj:code/shape/transform and each
    asset's file:size — was already resolved by an earlier `items` run and round-trips
    through the STAC-GeoParquet, so a pure metadata change (new links, new tree layout)
    costs one 4.5 MB download instead of ~8 h of network latency on rails. Use the full
    remote passes when the *tiles* change; use this when only the STAC shape changes.
    """
    import duckdb, json as _json
    con = duckdb.connect()
    con.execute("INSTALL spatial; LOAD spatial; INSTALL httpfs; LOAD httpfs; SET TimeZone='UTC';")
    rows = con.execute(f'''SELECT replace("grid:code", 'MGRS-', '') AS tile,
        ST_AsGeoJSON(ST_GeomFromWKB(geometry)) AS g,
        bbox.xmin, bbox.ymin, bbox.xmax, bbox.ymax,
        "proj:code", "proj:shape", "proj:transform",
        assets.planting."file:size", assets.harvest."file:size"
        FROM read_parquet('{PUB}/features/{year}/items.parquet')
        ORDER BY tile''' + (f" LIMIT {limit}" if limit else "")).fetchall()
    return [
        build_item(tile, year, _json.loads(g), [xmin, ymin, xmax, ymax], code, shape, transform,
                   sizes={"planting": ps, "harvest": hs})
        for tile, g, xmin, ymin, xmax, ymax, code, shape, transform, ps, hs in rows
    ]


def generate_items(year, workdir, limit=None, upload=True, workers=16,
                   from_parquet=False):
    """Per (tile, year): read COG header for proj, build item JSON, write to S3;
    accumulate a STAC-GeoParquet items.parquet and write it to S3. Outputs are
    NOT committed (the workdir should be gitignored).

    The two remote passes are pure network latency — ~1.3 s/tile serially, i.e.
    ~8 h for a year's 22.7k tiles — so both are parallelised: COG headers across
    *processes* (see _probe_proj), HEAD across threads. Run in-region (rails).

    ``from_parquet`` skips both passes and rebuilds the items from the published
    items.parquet — right for a metadata-only change, and runnable anywhere in a minute.
    """
    import json as _json
    d = Path(workdir) / "features" / str(year); d.mkdir(parents=True, exist_ok=True)
    places = load_places()
    if from_parquet:
        records = _records_from_published_parquet(year, limit)
        # A handful of assets came through the published parquet with no file:size (a HEAD
        # that failed on the original run). Only those get re-HEADed - tens, not ~45k.
        gaps = sorted({a["href"] for it in records for a in it["assets"].values()
                       if "file:size" not in a})
        if gaps:
            print(f"{year}: filling {len(gaps)} missing file:size via HEAD")
            with ThreadPoolExecutor(max_workers=workers) as pool:
                filled = dict(zip(gaps, pool.map(_head_size, gaps)))
            for it in records:
                for a in it["assets"].values():
                    if "file:size" not in a and filled.get(a["href"]) is not None:
                        a["file:size"] = filled[a["href"]]
        n_size = sum(1 for it in records for a in it["assets"].values() if "file:size" in a)
        n_missing = sum(1 for it in records for a in it["assets"].values() if "file:size" not in a)
        return _finish_items(d, year, records, places, n_size, n_missing, upload, workdir)
    import duckdb
    con = duckdb.connect()
    con.execute("INSTALL spatial; LOAD spatial; INSTALL httpfs; LOAD httpfs; SET TimeZone='UTC';")
    q = (f"SELECT tile_id, ST_AsGeoJSON(ANY_VALUE(geometry)) g, "
         f"ST_XMin(ANY_VALUE(geometry)) xmin, ST_YMin(ANY_VALUE(geometry)) ymin, "
         f"ST_XMax(ANY_VALUE(geometry)) xmax, ST_YMax(ANY_VALUE(geometry)) ymax "
         f"FROM read_parquet('{INDEX_PARQUET}') WHERE EXTRACT(year FROM time)={year} "
         f"GROUP BY tile_id ORDER BY tile_id" + (f" LIMIT {limit}" if limit else ""))
    rows = con.execute(q).fetchall()

    with ProcessPoolExecutor(max_workers=workers) as pool:
        proj = {r[0]: r[1:] for r in
                pool.map(_probe_proj, [(row[0], year) for row in rows], chunksize=8)
                if r is not None}
    records = []
    for tile_id, g, xmin, ymin, xmax, ymax in rows:
        if tile_id not in proj:
            continue
        proj_code, shape, transform = proj[tile_id]
        records.append(build_item(tile_id, year, _json.loads(g), [xmin, ymin, xmax, ymax],
                                  proj_code, shape, transform))
    # file:size via HTTP HEAD (cheap, parallel). file:checksum is deferred (see build_item).
    hrefs = sorted({a["href"] for it in records for a in it["assets"].values()})
    with ThreadPoolExecutor(max_workers=workers) as pool:
        sizes = dict(zip(hrefs, pool.map(_head_size, hrefs)))
    n_size = 0
    for it in records:
        for a in it["assets"].values():
            if sizes.get(a["href"]) is not None:
                a["file:size"] = sizes[a["href"]]; n_size += 1
    n_missing = sum(1 for h in hrefs if sizes.get(h) is None)
    return _finish_items(d, year, records, places, n_size, n_missing, upload, workdir)


def _finish_items(d, year, records, places, n_size, n_missing, upload, workdir):
    """Write the MGRS tree + grid catalogs + items.parquet, then upload the lot."""
    import json as _json
    by_gzd = {}
    for it in records:
        # Items live in the MGRS browse tree: features/<year>/<zone>/<gzd>/<iid>.json
        gzd = it["id"][:3]
        (d / gzd[:2] / gzd).mkdir(parents=True, exist_ok=True)
        (d / gzd[:2] / gzd / f"{it['id']}.json").write_text(_json.dumps(it))
        by_gzd.setdefault(gzd, []).append(it["id"])
    n_cat = _write_grid_catalogs(d, year, by_gzd, places)
    # STAC-GeoParquet (one row per item) via stac-geoparquet if available, else a simple parquet
    _write_stac_geoparquet(records, d / "items.parquet")
    print(f"{year}: wrote {len(records)} items ({n_size} asset file:size set, "
          f"{n_missing} unresolved; file:checksum deferred) + {n_cat} grid catalogs "
          f"+ items.parquet to {workdir}")
    if upload:
        base = f"s3://{S3_BUCKET}/{S3_PREFIX}/features/{year}"
        # Two passes so each gets the right Content-Type. The grid tree holds only
        # <iid>.json items and catalog.json nodes; items.parquet goes up separately.
        for include, ctype in ((f"*_{year}.json", "application/geo+json"),
                               ("*/catalog.json", "application/json")):
            subprocess.run(["aws", "s3", "cp", str(d), f"{base}/", "--recursive",
                            "--exclude", "*", "--include", include, "--quiet",
                            "--region", "us-west-2", "--content-type", ctype], check=True)
        subprocess.run(["aws", "s3", "cp", str(d / "items.parquet"),
                        f"{base}/items.parquet", "--quiet", "--region", "us-west-2"], check=True)
        print(f"{year}: uploaded the MGRS grid tree + items.parquet to {base}")
        print(f"NOTE: the pre-grid flat item prefix is now stale. After spot-checking the "
              f"new tree, remove it:\n  aws s3 rm {base}/items/ --recursive --region us-west-2")


def _write_grid_catalogs(d, year, by_gzd, places):
    """Write the zone + GZD catalog.json nodes over an already-written item tree."""
    counts = {g: len(v) for g, v in by_gzd.items()}
    by_zone = {}
    for gzd in sorted(by_gzd):
        by_zone.setdefault(gzd[:2], []).append(gzd)
    n = 0
    for zone, gzds in sorted(by_zone.items()):
        (d / zone / "catalog.json").write_text(
            json.dumps(build_zone_catalog(year, zone, gzds, counts, places), indent=2) + "\n")
        n += 1
        for gzd in gzds:
            (d / zone / gzd / "catalog.json").write_text(
                json.dumps(build_gzd_catalog(year, gzd, sorted(by_gzd[gzd]), places), indent=2) + "\n")
            n += 1
    return n


def _write_stac_geoparquet(items, path):
    try:
        import stac_geoparquet, pyarrow.parquet as pq
        rb = stac_geoparquet.arrow.parse_stac_items_to_arrow(items)
        pq.write_table(stac_geoparquet.arrow.stac_table_to_items and __import__("pyarrow").Table.from_batches(list(rb)) or rb, str(path))
    except Exception as e:  # noqa: BLE001
        # fallback: minimal columns so the index still exists
        print(f"WARNING: stac-geoparquet unavailable ({e}); writing a MINIMAL index parquet - "
              f"install stac-geoparquet and re-run before publishing {path}", file=sys.stderr)
        import pyarrow as pa, pyarrow.parquet as pq
        cols = {"id": [], "datetime": [], "bbox": [], "harvest_href": [], "planting_href": []}
        for it in items:
            cols["id"].append(it["id"]); cols["datetime"].append(it["properties"]["datetime"])
            cols["bbox"].append(json.dumps(it["bbox"]))
            cols["harvest_href"].append(it["assets"]["harvest"]["href"])
            cols["planting_href"].append(it["assets"]["planting"]["href"])
        pq.write_table(pa.table(cols), str(path))


def make_thumbnail(tile, year, workdir, upload=True):
    """Render a true-color (B04/B03/B02) preview of one tile's harvest composite to
    features/thumbnail.png (the collection thumbnail)."""
    import numpy as np
    import rasterio
    from rasterio.enums import Resampling
    from PIL import Image
    Path(workdir).mkdir(parents=True, exist_ok=True)
    out = Path(workdir) / "thumbnail.png"
    cog = f"{COG_BASE}/s2med_harvest/{tile}/{year}0101.tif"
    target = 600
    with rasterio.open(cog) as ds:
        scale = max(1, ds.width // target)
        w, h = ds.width // scale, ds.height // scale
        rgb = ds.read([3, 2, 1], out_shape=(3, h, w),
                      resampling=Resampling.average).astype("float32")  # R=B04, G=B03, B=B02
    arr = np.zeros((h, w, 3), dtype="uint8")
    for i in range(3):
        b = rgb[i]
        v = b[np.isfinite(b) & (b > 0)]
        if v.size:
            lo, hi = np.percentile(v, [2, 98])
            arr[..., i] = (np.clip((np.nan_to_num(b) - lo) / (hi - lo + 1e-6), 0, 1) * 255).astype("uint8")
    Image.fromarray(arr).save(out)
    print(f"wrote {out} ({w}x{h}) from harvest tile {tile} {year}")
    if upload:
        subprocess.run(["aws", "s3", "cp", str(out),
                        f"s3://{S3_BUCKET}/{S3_PREFIX}/features/thumbnail.png",
                        "--quiet", "--region", "us-west-2", "--content-type", "image/png"], check=True)
        print("uploaded features/thumbnail.png")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)
    c = sub.add_parser("collections"); c.add_argument(
        "--out", default=str(Path(__file__).resolve().parents[2] / "catalog"))
    it = sub.add_parser("items"); it.add_argument("year", type=int, choices=[2024, 2025])
    it.add_argument("--workdir", default=os.environ.get("WORK", "/tmp/ftw-features"))
    it.add_argument("--limit", type=int, default=None)
    it.add_argument("--workers", type=int, default=16,
                    help="parallel remote reads (COG header + HEAD); network-bound")
    it.add_argument("--no-upload", action="store_true")
    it.add_argument("--from-parquet", action="store_true",
                    help="rebuild items from the published items.parquet instead of re-reading "
                         "COG headers + HEADing assets (metadata-only changes; runs anywhere)")
    th = sub.add_parser("thumbnail"); th.add_argument("--tile", default="31UDP")
    th.add_argument("--year", type=int, default=2024)
    th.add_argument("--workdir", default=os.environ.get("WORK", "/tmp/ftw-features"))
    th.add_argument("--no-upload", action="store_true")
    pl = sub.add_parser("places", help="rebuild mgrs_places.json (duckdb+spatial, network)")
    pl.add_argument("--workdir", default=os.environ.get("WORK", "/tmp/ftw-features"))
    args = ap.parse_args(argv)
    if args.cmd == "collections":
        write_collections(args.out)
    elif args.cmd == "places":
        build_places(args.workdir)
    elif args.cmd == "thumbnail":
        make_thumbnail(args.tile, args.year, args.workdir, upload=not args.no_upload)
    else:
        generate_items(args.year, args.workdir, args.limit, upload=not args.no_upload,
                       workers=args.workers, from_parquet=args.from_parquet)
    return 0


if __name__ == "__main__":
    sys.exit(main())
