#!/usr/bin/env python3
"""Generate the STAC for the FTW field-boundary prediction-vectors collection.

One item per parquet partition (id = parquet filename stem), colocated with its
data on S3 via relative hrefs; countries split into multiple parquets get a
country sub-catalog. Each item carries an overview description, `table:columns`
(field definitions with spec links; the full `confidence` derivation lives there),
a per-year MapLibre style, a README, and a `derived_from` link to the prediction
Zarr. The collection adds a Portolan glob `data` asset, two collection PMTiles, and
the MapLibre styles.

Pure builders (bbox_to_polygon / title_for / build_item / build_collection) are
unit-tested. The CLI reads each parquet's bbox + row count (+ confidence stats from
the confidence-enriched parquet when present) and writes the tree under
staging/predictions/vectors/.

Usage:
    python3 build_vector_items.py --keys /tmp/keys.txt        # offline-ish
    python3 build_vector_items.py                              # list S3 itself
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

PUBLIC_BASE = "https://data.source.coop/ftw/global-data"
COLLECTION_HREF = f"{PUBLIC_BASE}/predictions/vectors"
DATA_REL = "alpha/results-by-admin-conf"          # relative to the collection dir
SRC_S3 = ("s3://us-west-2.opendata.source.coop/tge-labs/ftw-global-data/"
          "predictions/vectors/alpha/results-by-admin")
GITHUB = "https://github.com/fieldsoftheworld/ftw-data-catalog"
PMTILES_2025 = "https://data.source.coop/ftw/global-field-boundaries/pmtiles/ftw-global-fields-2025.pmtiles"
PMTILES_2024 = f"{PUBLIC_BASE}/predictions/vectors/alpha/2024_with_confidence.pmtiles"

PROJ_EXT = "https://stac-extensions.github.io/projection/v2.0.0/schema.json"
VECTOR_EXT = "https://stac-extensions.github.io/vector/v0.1.0/schema.json"
WEBMAP_EXT = "https://stac-extensions.github.io/web-map-links/v1.3.0/schema.json"
TABLE_EXT = "https://stac-extensions.github.io/table/v1.2.0/schema.json"
PARTITION_EXT = "https://portolan-sdi.github.io/stac-partition-extension/v1.0.0/schema.json"

# Field-definition specs (linked in each column description + via `describedby`).
FIBOA_CORE = "https://github.com/fiboa/specification/blob/main/core/README.md"
VECOREL_METRICS = "https://github.com/vecorel/geometry-metrics-extension"
VECOREL_ADMIN = "https://github.com/vecorel/administrative-division-extension"
FTW_URL = "https://fieldsofthe.world"
ZARR_URL = f"{PUBLIC_BASE}/predictions/zarr/collection.json"
CONF_COLLECTION_URL = f"{PUBLIC_BASE}/predictions/confidence/collection.json"
ADDCONF_URL = f"{GITHUB}/blob/main/scripts/confidence/add_confidence.py"

# Full `confidence` derivation detail lives in table:columns (not in the prose).
_CONF_COL_DESC = (
    "Derived; not part of the upstream model output. Modeled PRUE confidence on a "
    "0–100 scale, sampled at the field's point-on-surface from the 500 m confidence "
    f"COG ([predictions/confidence]({CONF_COLLECTION_URL})) and rescaled "
    "`raw / 0.578178 * 100`, clamped to 100 (0.578178 is treated as 100%, matching the "
    "FTW inference app; this centroid sample is the closest single value to the app's "
    "`confidence_mean`); **null where the field falls outside the modeled-confidence "
    "layer's coverage — i.e. no value there, not a low score** (the layer is sparse and "
    "conservative, fully covering mainly the 24 FTW-labelled training countries). "
    "Recommended reliability filter: "
    "`confidence >= 69` (raw 0.4). Reflects 500 m cell-level model reliability, not "
    f"individual-polygon geometric accuracy. Generated by [add_confidence.py]({ADDCONF_URL}) "
    "(+ process_partition.sh, run_rails.sh, make_pmtiles.py)."
)

TABLE_COLUMNS = [
    {"name": "id", "type": "string",
     "description": f"An identifier for the field. Must be unique per collection. ([fiboa core]({FIBOA_CORE}))"},
    {"name": "geometry", "type": "binary",
     "description": f"A geometry that reflects the footprint of the field, usually a Polygon. Default CRS is WGS84. ([fiboa core]({FIBOA_CORE}))"},
    {"name": "bbox", "type": "struct",
     "description": f"The bounding box of the field. ([fiboa core]({FIBOA_CORE}))"},
    {"name": "metrics:area", "type": "float",
     "description": f"Area of the field, in square meters (m²). Must be > 0. ([vecorel geometry-metrics]({VECOREL_METRICS}))"},
    {"name": "metrics:perimeter", "type": "float",
     "description": f"Perimeter of the field, in meters (m). Must be > 0. ([vecorel geometry-metrics]({VECOREL_METRICS}))"},
    {"name": "determination:datetime", "type": "timestamp",
     "description": f"The last timestamp at which the field did exist and was observed, in the UTC timezone. ([fiboa core]({FIBOA_CORE}))"},
    {"name": "determination:method", "type": "string",
     "description": f"The boundary creation method (one of: manual, surveyed, driven, auto-operation, auto-imagery, unknown). ([fiboa core]({FIBOA_CORE}))"},
    {"name": "admin:country_code", "type": "string",
     "description": f"ISO 3166-1 alpha-2 country code (aka admin0). Two-letter country code for the country that contains the field. ([vecorel administrative-division]({VECOREL_ADMIN}))"},
    {"name": "admin:subdivision_code", "type": "string",
     "description": f"ISO 3166-2 code for the principal subdivision (e.g. province or state, aka admin1) of a country that contains the field. Only the subdivision part of the code is stored. ([vecorel administrative-division]({VECOREL_ADMIN}))"},
    {"name": "confidence", "type": "float", "description": _CONF_COL_DESC},
]

# Shared prose pieces (confidence detail is in table:columns above).
_COLS_SHORT = ("id, geometry, bbox, metrics:area, metrics:perimeter, "
               "determination:datetime, determination:method, admin:country_code, "
               "admin:subdivision_code, confidence")
_DERIVATION = (
    f"A GeoParquet vector dataset is derived from the [prediction Zarr]({ZARR_URL}) by "
    "thresholding the softmax outputs for [non_field_background, field, field_boundaries] "
    "at 0.5 and polygonizing.")
_PROJECT = (f"Part of [Fields of the World]({FTW_URL}) — agricultural field boundaries "
            "delineated by the PRUE model from Sentinel-2 imagery.")

SCI_EXT = "https://stac-extensions.github.io/scientific/v1.0.0/schema.json"
PRUE_PAPER = "https://arxiv.org/abs/2603.27101"
FTW_PAPER = "https://arxiv.org/abs/2409.16252"
GUIDE_PAPER = "https://arxiv.org/abs/2602.08131"
FTW_BENCHMARK_DATA = "https://source.coop/kerner-lab/fields-of-the-world"
SCI_CITATION = ("Muhawenayo, G. et al. (2026). PRUE: A Practical Recipe for Field "
                "Boundary Segmentation at Scale. arXiv:2603.27101.")
SCI_PUBLICATIONS = [
    {"doi": "10.48550/arXiv.2409.16252",
     "citation": "Kerner, H. et al. (2025). Fields of the World: A Machine Learning "
                 "Benchmark Dataset for Global Agricultural Field Boundary Segmentation. "
                 "AAAI-2025. arXiv:2409.16252."},
    {"doi": "10.48550/arXiv.2603.27101",
     "citation": "Muhawenayo, G. et al. (2026). PRUE: A Practical Recipe for Field "
                 "Boundary Segmentation at Scale. arXiv:2603.27101."},
    {"doi": "10.48550/arXiv.2602.08131",
     "citation": "Corley, I. et al. (2026). Fields of The World: A Field Guide for "
                 "Extracting Agricultural Field Boundaries. arXiv:2602.08131."},
]
# How the model & training data work, synthesized from the three FTW papers.
BACKGROUND = (
    f"**How this was made.** Predictions come from the **PRUE** model ([Muhawenayo et al. "
    f"2026]({PRUE_PAPER})) — a U-Net segmentation model with composite losses and targeted "
    "augmentations that, in a benchmark of 18 models, scored **76% IoU / 47% object-F1** on "
    "the Fields of the World benchmark, outperforming instance-segmentation and geospatial-"
    f"foundation-model approaches. The **[Fields of the World benchmark]({FTW_BENCHMARK_DATA})** "
    f"(get the data on Source Cooperative; Kerner et al. 2025, AAAI, [arXiv:2409.16252]({FTW_PAPER})) "
    "pairs multi-date multispectral **Sentinel-2** imagery with instance/semantic field masks "
    "across **70,462 samples in 24 countries on four continents**; models pre-trained on it "
    "generalize better to held-out countries. PRUE is run over global Sentinel-2 planting/"
    "harvest median composites, and the softmax outputs are thresholded and polygonized into "
    f"these vectors. Downstream recipes (crop-type mapping, forest-loss attribution) are in the "
    f"FTW field guide ([Corley et al. 2026]({GUIDE_PAPER})).")


def _fields_phrase(count, conf):
    s = f"{count:,} field polygons" if count is not None else "field polygons"
    if conf:
        pct, mn, mx = conf
        s += (f"; {pct:.0f}% fall within the modeled-confidence layer's coverage "
              f"(confidence 0–100, here {mn:.0f}–{mx:.0f}; null elsewhere means outside "
              "the layer's coverage, not low confidence)")
    return s


# ── pure builders ────────────────────────────────────────────────────────────

def bbox_to_polygon(bbox):
    minx, miny, maxx, maxy = bbox
    return {"type": "Polygon", "coordinates": [[
        [minx, miny], [maxx, miny], [maxx, maxy], [minx, maxy], [minx, miny]]]}


def _country_name(cc):
    import pycountry
    c = pycountry.countries.get(alpha_2=cc)
    return c.name if c else cc


def title_for(stem, country_code):
    """Single-file partitions are named for the country; split partitions use an
    ISO-3166-2 subdivision code (underscore) -> "<Country> — <Subdivision>"."""
    import pycountry
    if "_" in stem:
        sub = pycountry.subdivisions.get(code=stem.replace("_", "-"))
        if sub:
            return f"{_country_name(country_code)} — {sub.name}"
        return stem
    return _country_name(country_code)


# Confidence ramp (0-100 scale, as stored in the per-country PMTiles `confidence`).
_RAMP = [0, "#d7191c", 70, "#fec379", 80, "#f3fabb", 90, "#cfecb0", 100, "#33a02c"]
_GREEN = "#33a02c"
_LEGEND_RAMP = {"title": "Confidence (0–100)", "unit": "%", "type": "ramp",
                "stops": [{"value": 0, "color": "#d7191c", "label": "0"},
                          {"value": 70, "color": "#fec379", "label": "70"},
                          {"value": 80, "color": "#f3fabb", "label": "80"},
                          {"value": 90, "color": "#cfecb0", "label": "90"},
                          {"value": 100, "color": "#33a02c", "label": "100"}]}

# The four per-item styles, named like the collection-level styles.
ITEM_STYLE_NAMES = ("2024", "2025", "confidence-2024", "confidence-2025")


def item_styles(stem):
    """Four MapLibre styles for one item's PMTiles — the same set as the collection:
    plain green field boundaries and a confidence ramp, for 2024 and 2025 (the
    per-country PMTiles carries a `2024` and a `2025` source-layer). Returns
    {style_name: style_dict}; each is written as `<stem>.<name>.style.json`."""
    url = f"pmtiles://./{stem}.pmtiles"
    conf = ["interpolate", ["linear"], ["to-number", ["get", "confidence"]], *_RAMP]
    out = {}
    for year in ("2024", "2025"):
        out[year] = {
            "version": 8, "name": f"{stem} — field boundaries ({year})",
            "metadata": {"portolan:legend": {"title": f"Field boundaries ({year})", "type": "category",
                          "stops": [{"color": _GREEN, "label": "Predicted field"}]},
                         "description": f"PRUE {year} field boundaries for {stem}, solid green."},
            "sources": {"data": {"type": "vector", "url": url}},
            "layers": [
                {"id": "fields-fill", "type": "fill", "source": "data", "source-layer": year,
                 "paint": {"fill-color": _GREEN, "fill-opacity": 0.2}},
                {"id": "fields-outline", "type": "line", "source": "data", "source-layer": year,
                 "paint": {"line-color": _GREEN, "line-width": 1}}]}
        out[f"confidence-{year}"] = {
            "version": 8, "name": f"{stem} — field boundaries by confidence ({year})",
            "metadata": {"portolan:legend": _LEGEND_RAMP,
                         "description": (f"PRUE {year} field boundaries for {stem}, with each field "
                                         "shaded by its confidence (0–100, red→green).")},
            "sources": {"data": {"type": "vector", "url": url}},
            "layers": [
                {"id": "fields-fill", "type": "fill", "source": "data", "source-layer": year,
                 "paint": {"fill-color": conf, "fill-opacity": 0.5}},
                {"id": "fields-outline", "type": "line", "source": "data", "source-layer": year,
                 "paint": {"line-color": conf, "line-width": 1}}]}
    return out


def item_description(stem, country_code, feature_count=None, conf=None):
    title = title_for(stem, country_code)
    return (
        f"Agricultural field boundaries for {title}. {_PROJECT} "
        f"This partition contains {_fields_phrase(feature_count, conf)}. "
        f"{_DERIVATION} Columns: {_COLS_SHORT} — see `table:columns` for definitions "
        "(including how `confidence` is derived).")


def build_item(stem, country_code, bbox, feature_count, is_split=False, conf=None):
    coll_up = "../../../"          # item dir -> collection dir
    root_up = "../../../../../"    # item dir -> catalog root
    parent = "./catalog.json" if is_split else f"{coll_up}collection.json"
    title = title_for(stem, country_code)
    self_href = (f"{COLLECTION_HREF}/{DATA_REL}/admin:country_code={country_code}/"
                 f"{stem}.json")
    return {
        "type": "Feature",
        "stac_version": "1.1.0",
        "stac_extensions": [PROJ_EXT, VECTOR_EXT, TABLE_EXT],
        "id": stem,
        "geometry": bbox_to_polygon(bbox),
        "bbox": bbox,
        "properties": {
            "title": title,
            "description": item_description(stem, country_code, feature_count, conf),
            "datetime": None,
            "start_datetime": "2024-01-01T00:00:00Z",
            "end_datetime": "2025-12-31T23:59:59Z",
            "admin:country_code": country_code,
            "proj:code": "EPSG:4326",
            "geoparquet:geometry_type": "Polygon",
            "geoparquet:feature_count": feature_count,
            "table:columns": TABLE_COLUMNS,
            # the Portolan browser reads this list to populate the style picker
            "portolan:styles": ["style-2025", "style-2024",
                                "style-confidence-2025", "style-confidence-2024"],
        },
        "collection": "vectors",
        "assets": {
            "data": {
                "href": f"./{stem}.parquet",
                "type": "application/vnd.apache.parquet",
                "title": f"{title} field boundaries (GeoParquet)",
                "roles": ["data"],
            },
            "pmtiles": {
                "href": f"./{stem}.pmtiles",
                "type": "application/vnd.pmtiles",
                "title": f"{title} field boundaries (PMTiles, 2024/2025 layers)",
                "roles": ["visual"],
            },
            "style-2025": {
                "href": f"./{stem}.2025.style.json", "type": "application/json",
                "title": "MapLibre style — field boundaries (2025)", "roles": ["style"]},
            "style-2024": {
                "href": f"./{stem}.2024.style.json", "type": "application/json",
                "title": "MapLibre style — field boundaries (2024)", "roles": ["style"]},
            "style-confidence-2025": {
                "href": f"./{stem}.confidence-2025.style.json", "type": "application/json",
                "title": "MapLibre style — by confidence (2025)", "roles": ["style"]},
            "style-confidence-2024": {
                "href": f"./{stem}.confidence-2024.style.json", "type": "application/json",
                "title": "MapLibre style — by confidence (2024)", "roles": ["style"]},
            "README": {
                "href": f"./{stem}.README.md",
                "type": "text/markdown",
                "title": f"{title} — README",
                "roles": ["metadata"],
            },
        },
        "links": [
            {"rel": "root", "href": f"{root_up}catalog.json", "type": "application/json"},
            {"rel": "collection", "href": f"{coll_up}collection.json", "type": "application/json"},
            {"rel": "parent", "href": parent, "type": "application/json"},
            {"rel": "self", "href": self_href, "type": "application/geo+json"},
            {"rel": "derived_from", "href": ZARR_URL, "type": "application/json",
             "title": "FTW prediction probabilities (Zarr)"},
            {"rel": "llms", "href": "./llms.txt", "type": "text/markdown",
             "title": "Agent/LLM usage guide"},
        ],
    }


def item_readme(stem, country_code, feature_count=None, conf=None):
    title = title_for(stem, country_code)
    lines = [
        f"# Field boundaries — {title}", "",
        _PROJECT, "",
        f"Partition `{stem}` (country `{country_code}`) contains "
        f"**{_fields_phrase(feature_count, conf)}**.", "",
        "## How it was made", "",
        f"{_DERIVATION} Each field also carries a derived `confidence` (0–100); see the "
        "`confidence` row in the table below for exactly how it is computed.", "",
        "## Columns", "",
        "Definitions use the [fiboa core](" + FIBOA_CORE + ") spec and the vecorel "
        "[geometry-metrics](" + VECOREL_METRICS + ") / "
        "[administrative-division](" + VECOREL_ADMIN + ") extensions "
        "(also machine-readable in the item's `table:columns`):", "",
        "| Field | Description |", "|---|---|",
        *[f"| `{c['name']}` | {c['description']} |" for c in TABLE_COLUMNS], "",
        "## Access", "",
        "```python",
        "import duckdb",
        'con = duckdb.connect(); con.execute("INSTALL spatial; LOAD spatial;")',
        f'u = "{COLLECTION_HREF}/{DATA_REL}/admin:country_code={country_code}/{stem}.parquet"',
        "con.sql(f\"SELECT count(*), avg(confidence) FROM read_parquet('{u}')\").show()",
        "```", "",
        "## Links", "",
        f"- Collection: {COLLECTION_HREF}/collection.json",
        f"- Derived from: [prediction Zarr]({ZARR_URL})",
        f"- [Fields of the World]({FTW_URL})", "",
    ]
    return "\n".join(lines) + "\n"


def build_collection(item_links, child_links):
    """item_links: [(stem, country_code)] single-file items; child_links:
    [country_code] split-country sub-catalogs."""
    links = [
        {"rel": "root", "href": "../../catalog.json", "type": "application/json",
         "title": "Fields of the World — Global"},
        {"rel": "parent", "href": "../../catalog.json", "type": "application/json"},
        {"rel": "self", "href": f"{COLLECTION_HREF}/collection.json", "type": "application/json"},
        {"rel": "license", "href": "https://creativecommons.org/licenses/by/4.0/",
         "type": "text/html"},
        {"rel": "derived_from", "href": ZARR_URL, "type": "application/json",
         "title": "FTW prediction probabilities (Zarr)"},
        {"rel": "llms", "href": "./llms.txt", "type": "text/markdown",
         "title": "Agent/LLM usage guide"},
        # field definitions follow these specs (also in table:columns)
        {"rel": "describedby", "href": FIBOA_CORE, "type": "text/html",
         "title": "fiboa core specification (id, geometry, bbox, determination:*)"},
        {"rel": "describedby", "href": VECOREL_METRICS, "type": "text/html",
         "title": "vecorel geometry-metrics extension (metrics:area, metrics:perimeter)"},
        {"rel": "describedby", "href": VECOREL_ADMIN, "type": "text/html",
         "title": "vecorel administrative-division extension (admin:*)"},
    ]
    # NOTE: PMTiles are exposed as visual *assets* (below). We deliberately do NOT also
    # add web-map-links `pmtiles` links — the Portolan browser auto-loads both and then
    # errors with "Layer ... already exists" (duplicate default layers per source-layer).
    for stem, cc in item_links:
        links.append({"rel": "item",
                      "href": f"./{DATA_REL}/admin:country_code={cc}/{stem}.json",
                      "type": "application/geo+json"})
    for cc in child_links:
        links.append({"rel": "child",
                      "href": f"./{DATA_REL}/admin:country_code={cc}/catalog.json",
                      "type": "application/json", "title": _country_name(cc)})

    return {
        "type": "Collection",
        "stac_version": "1.1.0",
        "stac_extensions": [PROJ_EXT, VECTOR_EXT, TABLE_EXT, SCI_EXT, PARTITION_EXT],
        # the Portolan browser reads this list to populate the style picker
        "portolan:styles": ["styles/2025", "styles/2024",
                            "styles/confidence-2025", "styles/confidence-2024"],
        "id": "vectors",
        "title": "FTW Global — Field Boundary Predictions (GeoParquet)",
        "description": (
            f"Global agricultural field-boundary polygons. {_PROJECT} ~3.2 billion field "
            "polygons across 195 countries, as cloud-native GeoParquet partitioned by "
            "country (admin, Hive layout), with per-country PMTiles for web visualization. "
            f"{_DERIVATION} Each field also carries a derived `confidence` (0–100). "
            f"Columns: {_COLS_SHORT} — see `table:columns` for definitions (including how "
            f"`confidence` is derived).\n\n{BACKGROUND}"),
        "sci:citation": SCI_CITATION,
        "sci:publications": SCI_PUBLICATIONS,
        "license": "CC-BY-4.0",
        "keywords": ["agriculture", "field boundaries", "Fields of the World",
                     "FTW", "global", "PRUE", "Sentinel-2", "confidence"],
        "providers": [
            {"name": "Taylor Geospatial Institute", "roles": ["producer", "licensor"],
             "url": "https://taylorgeospatial.org/"},
            {"name": "Microsoft AI for Good Research Lab",
             "roles": ["producer", "processor"],
             "url": "https://www.microsoft.com/en-us/research/group/ai-for-good-research-lab/"},
        ],
        "extent": {
            "spatial": {"bbox": [[-180.0, -60.0, 180.0, 84.0]]},
            "temporal": {"interval": [["2024-01-01T00:00:00Z", "2025-12-31T23:59:59Z"]]},
        },
        "summaries": {"proj:code": ["EPSG:4326"], "vector:geometry_types": ["Polygon"]},
        "table:columns": TABLE_COLUMNS,
        "partition:scheme": "hive",
        "partition:keys": [{"name": "admin:country_code", "type": "string"}],
        "links": links,
        "assets": {
            "data": {
                "href": f"./{DATA_REL}/admin:country_code=*/*.parquet",
                "type": "application/vnd.apache.parquet",
                "title": "Field-boundary polygons, partitioned by country (GeoParquet glob)",
                "description": "Portolan glob over all admin (country) partitions.",
                "roles": ["data"],
            },
            "pmtiles_2025": {
                "href": PMTILES_2025,
                "type": "application/vnd.pmtiles",
                "title": "Field boundaries 2025 (PMTiles, default web view)",
                "roles": ["visual"],
            },
            "pmtiles_2024_confidence": {
                "href": PMTILES_2024,
                "type": "application/vnd.pmtiles",
                "title": "Field boundaries 2024 with confidence (PMTiles)",
                "roles": ["visual"],
            },
            "styles/2025": {
                "href": "./styles/2025.json", "type": "application/json",
                "title": "Field boundaries (2025) — default", "roles": ["style"]},
            "styles/2024": {
                "href": "./styles/2024.json", "type": "application/json",
                "title": "Field boundaries (2024)", "roles": ["style"]},
            "styles/confidence-2025": {
                "href": "./styles/confidence-2025.json", "type": "application/json",
                "title": "Field boundaries by confidence (2025)", "roles": ["style"]},
            "styles/confidence-2024": {
                "href": "./styles/confidence-2024.json", "type": "application/json",
                "title": "Field boundaries by confidence (2024)", "roles": ["style"]},
            "thumbnail": {
                "href": f"{PUBLIC_BASE}/docs/global-ftw-map.png",
                "type": "image/png",
                "title": "Global field-boundary predictions map",
                "roles": ["thumbnail", "overview"]},
            "documentation": {
                "href": "./llms.txt", "type": "text/markdown",
                "title": "Agent/LLM usage guide", "roles": ["documentation"]},
            "README": {"href": "./README.md", "type": "text/markdown",
                       "title": "Human-readable README", "roles": ["metadata"]},
        },
    }


def build_country_catalog(country_code, child_stems):
    return {
        "type": "Catalog",
        "stac_version": "1.1.0",
        "id": f"vectors-{country_code}",
        "title": f"{_country_name(country_code)} — field boundary predictions",
        "description": (
            f"Field-boundary predictions for {_country_name(country_code)}, split into "
            f"{len(child_stems)} admin-subdivision partitions. {_PROJECT} {_DERIVATION}"),
        "links": [
            {"rel": "root", "href": "../../../../../catalog.json", "type": "application/json"},
            {"rel": "parent", "href": "../../../collection.json", "type": "application/json"},
            {"rel": "self",
             "href": f"{COLLECTION_HREF}/{DATA_REL}/admin:country_code={country_code}/catalog.json",
             "type": "application/json"},
            {"rel": "derived_from", "href": ZARR_URL, "type": "application/json",
             "title": "FTW prediction probabilities (Zarr)"},
            {"rel": "llms", "href": "./llms.txt", "type": "text/markdown"},
            *[{"rel": "item", "href": f"./{stem}.json", "type": "application/geo+json"}
              for stem in child_stems],
        ],
    }


# ── CLI: read parquet metadata + write the tree ──────────────────────────────

def _read_keys(keys_path):
    if keys_path:
        return [l.strip() for l in Path(keys_path).read_text().splitlines() if l.strip()]
    out = subprocess.run(
        ["aws", "s3", "ls", "--no-sign-request", "--recursive", "--region",
         "us-west-2", SRC_S3 + "/"], check=True, capture_output=True, text=True).stdout
    keys = []
    for line in out.splitlines():
        p = line.split()[-1]
        if p.endswith(".parquet"):
            keys.append(p.split("/results-by-admin/", 1)[1])
    return keys


_S3FS = None
_S3BASE = "us-west-2.opendata.source.coop/tge-labs/ftw-global-data/predictions/vectors/alpha"


def _fs():
    global _S3FS
    if _S3FS is None:
        import pyarrow.fs as pafs
        _S3FS = pafs.S3FileSystem(anonymous=True, region="us-west-2")
    return _S3FS


def _bbox_count(pf):
    geo = json.loads(pf.metadata.metadata[b"geo"])
    return geo["columns"][geo["primary_column"]]["bbox"], pf.metadata.num_rows


def _confidence_stats(pf, count):
    """(pct_non_null, min, max) for the `confidence` column from footer stats, or None."""
    md = pf.metadata
    names = [md.schema.column(i).path for i in range(md.num_columns)]
    if "confidence" not in names or not count:
        return None
    ci = names.index("confidence")
    nulls, mn, mx, seen = 0, None, None, False
    for rg in range(md.num_row_groups):
        st = md.row_group(rg).column(ci).statistics
        if st is None:
            continue
        seen = True
        if st.has_null_count:
            nulls += st.null_count
        if st.has_min_max:
            mn = st.min if mn is None else min(mn, st.min)
            mx = st.max if mx is None else max(mx, st.max)
    if not seen or mn is None:
        return None
    return (100.0 * (count - nulls) / count, mn, mx)


def _item_stats(cc, fname):
    """(bbox, count, conf) — read the confidence-enriched parquet when it exists
    (also yields confidence stats); else fall back to the original (conf=None)."""
    import pyarrow.parquet as pq
    fs = _fs()
    conf_path = f"{_S3BASE}/results-by-admin-conf/admin:country_code={cc}/{fname}"
    try:
        with fs.open_input_file(conf_path) as f:
            pf = pq.ParquetFile(f)
            bbox, count = _bbox_count(pf)
            return bbox, count, _confidence_stats(pf, count)
    except (FileNotFoundError, OSError):
        orig = f"{_S3BASE}/results-by-admin/admin:country_code={cc}/{fname}"
        with fs.open_input_file(orig) as f:
            pf = pq.ParquetFile(f)
            bbox, count = _bbox_count(pf)
            return bbox, count, None


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--keys", help="file with parquet keys (else list S3)")
    ap.add_argument("--out", default=str(Path(__file__).resolve().parents[2]
                                         / "staging/predictions/vectors"))
    args = ap.parse_args(argv)

    keys = _read_keys(args.keys)
    from collections import defaultdict
    by_cc = defaultdict(list)
    for k in keys:
        cc = k.split("admin:country_code=", 1)[1].split("/", 1)[0]
        fname = k.rsplit("/", 1)[-1]
        by_cc[cc].append(fname)

    out = Path(args.out)
    item_links, child_links = [], []
    n_items = 0
    for cc, fnames in sorted(by_cc.items()):
        is_split = len(fnames) > 1
        cdir = out / DATA_REL / f"admin:country_code={cc}"
        cdir.mkdir(parents=True, exist_ok=True)
        stems = []
        for fname in sorted(fnames):
            stem = fname[:-len(".parquet")]
            stems.append(stem)
            bbox, count, conf = _item_stats(cc, fname)
            item = build_item(stem, cc, bbox, count, is_split=is_split, conf=conf)
            (cdir / f"{stem}.json").write_text(json.dumps(item, indent=2))
            for sname, sdict in item_styles(stem).items():
                (cdir / f"{stem}.{sname}.style.json").write_text(json.dumps(sdict, indent=2))
            (cdir / f"{stem}.README.md").write_text(item_readme(stem, cc, count, conf))
            n_items += 1
            if not is_split:
                item_links.append((stem, cc))
        (cdir / "llms.txt").write_text(_country_llms(cc, stems))
        if is_split:
            cat = build_country_catalog(cc, stems)
            (cdir / "catalog.json").write_text(json.dumps(cat, indent=2))
            child_links.append(cc)
        print(f"{cc}: {len(fnames)} item(s){' [split]' if is_split else ''}")

    col = build_collection(item_links, child_links)
    out.mkdir(parents=True, exist_ok=True)
    (out / "collection.json").write_text(json.dumps(col, indent=2))
    (out / "llms.txt").write_text(_collection_llms(len(by_cc), n_items))
    print(f"\nOK: collection + {n_items} items across {len(by_cc)} countries "
          f"({len(child_links)} split) -> {out}")
    return 0


def _columns_md():
    return [f"- `{c['name']}` ({c['type']}): {c['description']}" for c in TABLE_COLUMNS]


def _country_llms(cc, stems):
    name = _country_name(cc)
    return "\n".join([
        f"# FTW field-boundary predictions — {name}", "",
        _PROJECT, "",
        f"Country code: {cc}. Partitions: {len(stems)}.", "",
        _DERIVATION, "",
        "## Columns",
        "Definitions use the fiboa core spec and vecorel extensions "
        f"([fiboa core]({FIBOA_CORE}), [geometry-metrics]({VECOREL_METRICS}), "
        f"[administrative-division]({VECOREL_ADMIN})):",
        *_columns_md(), "",
        "## Files", *[f"- `{s}.parquet` (GeoParquet) + `{s}.pmtiles` (vector tiles, "
                      "2024/2025 layers) + 4 `{s}.*.style.json` (green/confidence × 2024/2025)"
                      .replace("{s}", s) for s in stems],
    ]) + "\n"


def _collection_llms(n_countries, n_items):
    return "\n".join([
        "# FTW Global — Field Boundary Predictions (GeoParquet)", "",
        _PROJECT, "",
        f"~3.2 billion field polygons across {n_countries} countries in {n_items} "
        "country/subdivision partitions. GeoParquet partitioned by country; query the "
        f"whole set with the glob `{DATA_REL}/admin:country_code=*/*.parquet`.", "",
        "## How the vectors are made", _DERIVATION, "",
        "## Model & training data", BACKGROUND, "",
        "## Columns",
        "Definitions use the fiboa core spec and vecorel extensions "
        f"([fiboa core]({FIBOA_CORE}), [geometry-metrics]({VECOREL_METRICS}), "
        f"[administrative-division]({VECOREL_ADMIN})):",
        *_columns_md(), "",
        "## Visualization",
        "Two collection PMTiles: 2025 (default) and 2024-with-confidence; per-country "
        "PMTiles per partition (2024/2025 year layers). Styles in `styles/` color by "
        "confidence (red→green, 0–100) with the recommended >=69 filter.", "",
    ]) + "\n"


if __name__ == "__main__":
    sys.exit(main())
